### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cweagans** [mas-cli/mas#11]
Just wanted to say thanks for `mas`. I just added it to my workstation configuration over at https://github.com/cweagans/workstation and this is **really** useful for those apps that `brew cask` can't handle.

This is really _really_ awesome. Thank you!

**Comment by timsutton** [comment]
:+1:!

**Comment by cybertk** [comment]
+1

**Comment by yayao** [comment]
+1

**Comment by orta** [comment]
Yep - this is a great idea, good job

**Comment by reitermarkus** [comment]
👍

Finally, I can abandon my AppleScript-y solution. =)

**Comment by stalinkay** [comment]
+1

**Comment by sibte** [comment]
+1

**Comment by hzb** [comment]
+1

**Comment by istx25** [comment]
100% agree. Thanks for the hard work!

**Comment by phatblat** [comment]
Your thanks is much appreciated, but certainly goes to the other contributors such as @argon and @rodionovd who have made this project happen. It's been a bit quiet lately, but there will be some new releases coming soon. Also, if you're interested in contributing, please open an issue requesting to be added to the project.
