### ISSUE TITLE
Time to fork?

### ISSUE THREAD

**Issue by mandrean** [mas-cli/mas#115]
This is a great and popular project that just needs some maintenance love to stay relevant, but since @rodionovd seems to ignore all issues/pull requests/adding maintainers and any communication at all, I think the community needs to team up and create a proper fork to keep moving forward.

Maybe @phatblat and @Jake3231 can sync on their great PRs and use that as a starting point for the new fork?

**Comment by Jake3231** [comment]
Thank you @mandrean. I would agree that this is a great project, but certainly could use a bit of attention in terms of maintenance.

I'd be more than happy to do whatever I can to help improve this project, including syncing my pull request. Alternatively, I found @rodionovd's email address, and I could contact him directly about this.

**Comment by phatblat** [comment]
Forking is an option that I think is worth considering, but before we do that I'd like to see if we can have @rodionovd add some of us as maintainers. It would be a shame to have to move away from the mac-cli org.

**Comment by phatblat** [comment]
No need to fork! 😄  I'm now a maintainer on this repo and will be working on the issue/PR backlog.

**Comment by mandrean** [comment]
A W E S O M E @phatblat 

😊
