### ISSUE TITLE
Add phatblat as org owner

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#116]
@rodionovd, you have probably been busy with other projects and life in general, and there's no shame in that, but myself and others would like to help on this project!

Can you please add me as a mas-cli organization owner? That way I can help with adding other contributors to the project as there is interest. I'd prefer to keep the activity here in this org/repo, but without your help we are going to have to move new activity to a fork of the project.

Relates to: #115, #113, #110

**Comment by rodionovd** [comment]
Hello @phatblat! Thank you for getting in touch, I do really appreciate your (and others) efforts in bringing the project back to life.

As you may have guessed already, I don't have enough capacity for maintaining mas anymore (never had actually; it was a mistake to become a maintainer in the first place), so I dropped an email to @argon and asked him to add a few new members to this organization. I hope to receive an email from Andrew soon but if there won't be any feedback in a couple of days, I'll add you as a new admin of mas-cli so you can keep the project going and add more ppl if needed

**Comment by phatblat** [comment]
Thanks, @rodionovd! Hope things are going well for you.

**Comment by rodionovd** [comment]
@phatblat thank you! It's just a general lack of time and mental energy on my end...

Just wanted to make sure that your are aware of (and agree to) the rules described in #47. Then I'll be able to make you a new admin of mas-cli.

**Comment by phatblat** [comment]
Yes, I agree. I can add those conditions to a new COBTRIBUTING.md so they don’t get buried in the issue history.

**Comment by rodionovd** [comment]
That would be just great! 

I sent you an invite to join the organization. Welcome to the team, Ben!

**Comment by phatblat** [comment]
Thanks, @rodionovd!
