### ISSUE TITLE
`signin` fails over ssh

### ISSUE THREAD

**Issue by messenger82** [mas-cli/mas#12]
entering "mas signin me@gmail.com "password" does not return an error.  But when attempting to run "mas install 123456" the MAS GUI pops up.  Is signin not happening?

**Comment by argon** [comment]
Which version of OSX are you running?

—A

**Comment by messenger82** [comment]
We're replicated the behavior on 10.11.3 and 10.11.2.   Absolutely awesome app BTW.  If this work for us it's literally going to save hundreds of hours per year.

**Comment by MGatner** [comment]
Colleague of messenger82. We are attempting to deploy installations to multiple labs of computers. Any interactions that require the App Store (install, list, outdated, signin, signout, upgrade) when run remotely (e.g. via ssh login) return "Illegal instruction: 4" - other "local" commands (account, help, version) run fine.

*Not signed in yet (`mas signin`)
*OS X 10.10.5
*Xcode 7.2
*Homebrew installed manually in /usr/local/homebrew
*No errors on `brew install argon/mas/mas`

Thanks for any help; this app has great potential for mass-management and I would love to see it working for deployment purposes.

**Comment by MichalMMac** [comment]
From quick test I figured out I need this option enabled –> System Preferences -> App Store -> Free Downloads -> Save Password

btw why not download Xcode from developer portal and deploy it with Munki or ARD?

**Comment by timsutton** [comment]
@MichalMMac I noticed something like that too. Then I signed out, rebooted and I'm no longer able to reproduce it - it's working right now for me on a 10.11.4 beta 4 machine with the setting still set to "Require password." However, I find that in order for the installations to work reliably, I need to first do `mas signout` and then a `mas signin` in order for it to work. Multiple installations usually work ok after that point without the signout/signin.

**Comment by messenger82** [comment]
@MichalMMac That seemed to resolve one of our two issues, very excited about the progress.  Issuing mas upgrade now updates.  As for using Munki or ARD, @MGatner has developed an internal tool that's largely the same concept for pushing packages.  We're really only using Homebrew for grabbing test media.  

Perhaps this warrants a second issue but we still have the ssh bug.  When connecting remotely to a machine we get an "Illegal instruction: 4" error.  For instance "mas list" will generate that.  I noticed version 1.1.3 discussed solving that?

**Comment by argon** [comment]
This is fixed by using the `reattach-to-user-namespace` tool found in Homebrew. Please see the readme for more information
