### ISSUE TITLE
Uninstalling app

### ISSUE THREAD

**Issue by buzdin** [mas-cli/mas#13]
How is it possible to uninstall packages with this cli tool?
Is this something, which could be developed?

**Comment by argon** [comment]
I don't believe it is something that is supported by the Mac App Store directly.

What is your use case?

**Comment by buzdin** [comment]
sorry for my ignorance, probably it is not supported, have not checked :)

I was thinking of removing unrelated apps on a fresh macos, like garageband and imovie

**Comment by argon** [comment]
You would be better off scripting the deletion of those specific applications. See: http://smallbusiness.chron.com/delete-garageband-mac-29847.html

**Comment by buzdin** [comment]
thanks!
