### ISSUE TITLE
version in search?

### ISSUE THREAD

**Issue by brianmorton** [mas-cli/mas#130]
is it possible to see what the version being offered in the mac app store is through search (or other means)?

I don't mean `outdated`/`list`...

Consider:
```
$ mas search quip
1003160018 Quip
1002623276 Quiplash
```

Is there a way to get those results with the version number? Do I need to hack on this a bit and send a PR?

**Comment by brianmorton** [comment]
ping @phatblat

**Comment by brianmorton** [comment]
added PR https://github.com/mas-cli/mas/pull/131 - hope that implementation is alright.

**Comment by phatblat** [comment]
Nice! I'll check it out
