### ISSUE TITLE
Running mas creates "default.profraw" file

### ISSUE THREAD

**Issue by dentarg** [mas-cli/mas#134]
```
$ ls default.profraw
ls: default.profraw: No such file or directory

$ mas version
1.4.0

$ ls default.profraw
default.profraw
```

```
$ file default.profraw
default.profraw: LLVM raw profile data, version 4
```

I'm on macOS 10.12.6 (16G1212)

**Comment by dentarg** [comment]
Same thing happens on macOS 10.13.3 (17D47)

**Comment by phatblat** [comment]
What version of mas are you using?

**Comment by dentarg** [comment]
@phatblat 1.4.0 (thought that would be clear from the repro, sorry)

**Comment by phatblat** [comment]
Oh, duh. Sorry, I looked right over that. 🙄 

Tried to reproduce this on macOS 10.13.3 (17D2047) (iMac Pro) and didn't get a `default.profraw` file with either 1.4.0 or 1.3.1. However, on 10.13.3 (17D47) (MacBook) I got one right away in the current directory from version 1.3.1 by simply running `mas version` like you did. I deleted the `default.profraw` file and ran several more command through both versions and didn't get a new file.

This should be easy to resolve.

**Comment by anderscarling** [comment]
I get this for home-brew installed (from bottle) mas on high sierra as well, seems to be related to a build setting for generating code coverage files that probably should only be enabled for test builds.

Some info is available at https://github.com/termux/termux-packages/issues/1672

**Comment by phatblat** [comment]
@dentarg This is fixed now in 1.4.1. Thanks for the report!

**Comment by 4cm4k1** [comment]
Ah, thank you! I was wondering what was causing that.

**Comment by matteocorti** [comment]
The problem has reappeared (at least with 1.4.3)

```
$ ls -l default.profraw 
ls: default.profraw: No such file or directory
$ mas version
1.4.3
$ ls -l default.profraw 
-rw-r--r--  1 corti  staff  13256 Nov 13 16:30 default.profraw
```
