### ISSUE TITLE
mas 1.4.1 on El Capitan requires Xcode.app 9.0 (i.e., [High] Sierra)

### ISSUE THREAD

**Issue by jdickey** [mas-cli/mas#138]
```console
$ brew upgrade mas
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
mas 1.4.1
mas: A full installation of Xcode.app 9.0 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode 9.0 cannot be installed on macOS 10.11.
You must upgrade your version of macOS.
Error: mas: An unsatisfied requirement failed this build.
%
```

We, and several other development shops we know, are still running El Capitan, awaiting that hopefully not-distant day when an OS update solves more problems for more people than it causes. We'd expected that to come with the follow-on to Sierra; now our hopes have shifted to macOS 10.13.16 on current trends.

I looked at the changelog, and resolving Issue #114 appeared to be the most obvious thing that orphaned those dependent on stable operating system versions. I'm all for "modern standards"; it's what I've built most of a 39-year career on, but not at the expense of breaking irreplaceable workflows. If that truly is the only reason Xcode 9 is now required, can someone posit a more compelling reason for throwing Apple-supported operating system users under the bus?

Current system:

* OS X 10.11.6
* Homebrew 1.5.4
* mas 1.3.1
* Xcode 8.2.1 (8C1002)

**Comment by phatblat** [comment]
Sorry about that. The project has been updated to use Swift 4, which requires Xcode 9, but Homebrew only built bottles for [`sierra` and `high_sierra`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mas.rb#L8), so it's falling back to try to build from source on your box. I will look into what can be done to build a [bottle](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md) for El Capitan. I'd hate to revert back to Swift 3 as this projects dependencies are now on 4.

**Comment by phatblat** [comment]
@jdickey I [confirmed](https://discourse.brew.sh/t/how-to-build-bottle-for-older-macos-version/1719/2) with the Homebrew team that brew bottles are only built for the current macOS version, so they can't build bottles for macOS versions that don't support the Xcode version required by the formula.

To work around this limitation I've created [`mas-cli/tap`](https://github.com/mas-cli/homebrew-tap) and published brew bottles to [Bintray](https://bintray.com/phatblat/mas-bottles/mas).

Can you try installing mas from this new tap?

```
brew install mas-cli/tap/mas
```

I'm going to close this issue, but feel free to open a new one if you have any trouble with the tap!
