### ISSUE TITLE
What's the difference between "id: Install" and "id: 0"?

### ISSUE THREAD

**Issue by piotr-yuxuan** [mas-cli/mas#139]
I noticed a change in my Brewfile:

``` diff
-mas "macOS High Sierra", id: Install
+mas "Install macOS High Sierra", id: 0
```

Does it mean the update has been downloaded / installed?

**Comment by phatblat** [comment]
Both look wrong. "Install" is not an app ID and the actual id for "macOS High Sierra" (the name in the Mac AppStore) is `124628474`. I'm not sure whether this is a bug in Homebrew or mas, but we may need [special handling for OS installers](https://github.com/mas-cli/mas/issues/106#issuecomment-374810186).

**Comment by phatblat** [comment]
I'm fairly certain this is a bug as I just got this when dumping my `Brewfile`:

```
...
mas "installed apps found", id: No
```

**Comment by rgoldberg** [comment]
Can we close this?

See https://github.com/mas-cli/mas/issues/106#issuecomment-2348697690

**Comment by rgoldberg** [comment]
Is this problem solely for macOS installers, or does it also affect normal apps?

**Comment by rgoldberg** [comment]
Closing, as this was fixed a long time ago by https://github.com/Homebrew/homebrew-bundle/pull/349.

**Comment by piotr-yuxuan** [comment]
A bit late to the party, but thanks again @rgoldberg for the follow-pup :)
