### ISSUE TITLE
Xcode CLI Tools are not distributed via MAS

### ISSUE THREAD

**Issue by EmilVarona** [mas-cli/mas#143]
I don't know if this is by design but I had Xcode 9.2 installed using `mas`. After looking at the homebrew output, I noticed it mentioned `Your Xcode (9.2) is outdated`. I had run `mas upgrade` at least 4 consecutive days prior to that.  
Any reason that Xcode was not picked up as changed by mas or am I missing something?

**Comment by RotsiserMho** [comment]
I encountered a similar issue resulting in the error on the terminal: "Error: Your Command Line Tools are too outdated. Update them from Software Update in the App Store". The App Store then shows that the Command Line Tools need to be installed. "mas upgrade" says "Everything is up-to-date".

**Comment by phatblat** [comment]
@EmilVarona what version of macOS are you using?

Presently, the CLI tools are not distributed through the Mac App Store, but must be downloaded manually through the "[More](https://developer.apple.com/download/more/)" area of the Apple Developer portal. This is made easier through [xcode-install](https://github.com/KrauseFx/xcode-install) gem. They can also be updated using the `softwareupdate` command.

In 10.14, the CLI tools are updated through the new Software Update pane of System Preferences.
