### ISSUE TITLE
Upgrade specific app

### ISSUE THREAD

**Issue by enderahmetyurt** [mas-cli/mas#17]
Need to upgrade just one app instead all list which return `mas outdated`

It should be `mas upgrade -a iMovie`

**Comment by argon** [comment]
`mas install <imovie identifier>` will upgrade just one app.

**Comment by enderahmetyurt** [comment]
it calls install action. I need to upgrade the app.

**Comment by argon** [comment]
Install has the same effect as upgrade. There is no difference.
