### ISSUE TITLE
Homebrew still points to 1.4.1

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [mas-cli/mas#174]
If I try to upgrade `mas` through `brew upgrade mas` it tells me, that there is no new version, but in fact version `1.4.2` is already released.

    $ brew update
    Already up-to-date.
    $ brew upgrade mas
    Error: mas 1.4.1 already installed

What needs to be done, that an upgrade via `brew` to version `1.4.2` will work?
Is this even an issue for this repo or should it be moved to homebrew?

**Comment by CaptainYukinoshitaHachiman** [comment]
Maybe we need to update the information at brew.

**Comment by ThomasKoppensteiner** [comment]
The [PR](https://github.com/Homebrew/homebrew-core/pull/31058) for merging the formula for `mas 1.4.2` was closed (declined).
Now the plan is to release `1.4.3`.

**Comment by rgoldberg** [comment]
Resolved by #169
