### ISSUE TITLE
many commands do not work when run as root

### ISSUE THREAD

**Issue by bretbenz** [mas-cli/mas#18]
Most apps run remotely via Apple Remote Desktop return the standard output to ARD. This app does not. I was hoping to deploy this on all my systems and use ARD to send a "mas outdated" command but nothing comes back.

**Comment by bretbenz** [comment]
Actually, this only happens when run as root. Using any other admin account works fine.

**Comment by KillerZebra** [comment]
How do you run these commands in ARD? Every time I try it says "/bin/bash: line 1: mas: command not found"

**Comment by timsutton** [comment]
The `mas` binary is probably not in the `PATH` used by the shell as invoked by ARD. Just specify the full path (which if it's a brew install would be `/usr/local/bin/mas`).

**Comment by argon** [comment]
Based on my understanding of the permissions `mas` will never work under root. I'm going to close this issue.
