### ISSUE TITLE
[BUG] 1.5.0 Release PKG is borked

### ISSUE THREAD

**Issue by apizz** [mas-cli/mas#194]
**Describe the bug**
v 1.5.0 mas-cli PKG installer produces error: is missing mas_temp.pkg per Suspicious Package

**To Reproduce**
1. Download latest mas-cli PKG version
2. Launch Suspicious Package
3. Open PKG in Suspicious Package

**Expected behavior**
A PKG without any errors

**Screenshots**
![screen shot 2019-01-03 at 8 59 45 am](https://user-images.githubusercontent.com/11789931/50641451-f46d5500-0f35-11e9-8ccf-23a7c9459862.png)

**Desktop (please complete the following information):**
 - mas version: N/A
 - macOS version: **10.12.6**
 - How did you install mas? N/A

**Additional context**

**Comment by phatblat** [comment]
Thanks for catching this! Not sure what happened. The pkg for 1.5 is only 4KB whereas the previous one was 3.5MB.

**Comment by phatblat** [comment]
This is fixed now @apizz
