### ISSUE TITLE
[BUG] Lucky command gives JSON error

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#204]
**Describe the bug**
The `lucky` commands no longer works and always gives the same error.

**To Reproduce**
1. Run the command: `mas lucky clean`
1. Observe error

**Expected behavior**
mas will install the app [Clean](https://itunes.apple.com/us/app/clean/id418412301?mt=12)

**Actual behavior**
Error: Unable to parse response JSON

**Screenshots**
![screen shot 2019-01-14 at 9 30 41 pm](https://user-images.githubusercontent.com/28851/51158868-a9134a80-1843-11e9-914f-683cd5608d11.png)

**Desktop (please complete the following information):**
 - mas version 1.6.0
 - macOS version: 10.14.2
 - How did you install mas? [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)

**Additional context**
This broke in 1.6.0 #201

If you specify an invalid search string - one that won't result in at least one search result - a different, but expected error appears:.

```
mas lucky 111
No results found
Error: No results found
```

**Comment by betraying** [comment]
same here
<img width="335" alt="screen shot 2019-01-15 at 11 04 15 pm" src="https://user-images.githubusercontent.com/15680036/51206743-e4804880-1919-11e9-820a-b2825d0b1a7b.png">

**Comment by phatblat** [comment]
Thanks, @betraying. This was a silly little mistake. I'll have a fix out later this week.
