### ISSUE TITLE
brew bundle integration

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#21]
Thinking about being able to specify mac app store apps in my `Brewfile` and have them be installed as part of brew bundle.

**Comment by argon** [comment]
That sounds like an interesting idea. I'd be interested to see what anyone can come up with for this.

**Comment by mikemcquaid** [comment]
I'm one of the Homebrew maintainers and am up for implementing this. @argon how would you feel about `mas` being part of the main Homebrew repository? If you're 🆗 with that I'll create a PR.

**Comment by argon** [comment]
@mikemcquaid could you explain a little more how you'd see this working please?

**Comment by mikemcquaid** [comment]
@argon I'd see the following steps (if they were all 🆗 with you):

1. `mas` be added to the `homebrew/core` repository so anyone can `brew install mas`.
2. `brew bundle dump` will dump your App Store apps to a `Brewfile` using `mas list` and install them using `mas install` (if you have `mas` already installed).

**Comment by argon** [comment]
@mikemcquaid that sounds great. I guess the main impact to me would be needing a PR to `homebrew/core` whenever I release a new version?

**Comment by mikemcquaid** [comment]
@argon Yep, basically, although the community may notice and pick that up for you.

**Comment by argon** [comment]
@mikemcquaid Awesome 🆗. Can't wait to see what the future holds.

**Comment by mikemcquaid** [comment]
@argon Well done on an awesome project. I had it bookmarked for a while and thought I was going to be disappointed by an ugly hack but it's pretty great 👏

**Comment by timsutton** [comment]
Guilty as charged (!), that's my Apple radar I opened today asking Apple to write a supported CLI tool to do what the `mas` tool allows.

I think this project is awesome and have had good results with it, but it would be great if it didn't require using internal frameworks. Feel free to dupe!

**Comment by mikemcquaid** [comment]
@argon Not merged yet but https://github.com/Homebrew/homebrew-core/pull/493 https://github.com/Homebrew/homebrew-bundle/issues/172

**Comment by jadengore** [comment]
@mikemcquaid This is merged now correct?
