### ISSUE TITLE
`open` displays a spurious error dialog after opening `App Store.app`

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#217]
**Describe the bug**
Using the `mas open` command works to open the app store app, but an error dialog always appears a few seconds later.

**To Reproduce**
1. Run `mas open` with no appID
2. Observe the app store app open
3. Observe "Loading" spinner in center of 
4. See error dialog saying "

**Expected behavior**
The app store app opens to the "★ Discover" tab.

**Actual behavior**
An error dialog appears after a few seconds with the following message:

> Cannot Connect to App Store
> [Retry] [**OK**]

**Screenshots**
This is the dialog that appears after a few seconds.
![screen shot 2019-02-04 at 2 11 10 pm](https://user-images.githubusercontent.com/28851/52309854-9f6e9580-295e-11e9-9ea3-19239677a24d.png)

**Desktop (please complete the following information):**
 - mas version 1.6.22
 - macOS version: 10.14.3
 - How did you install mas? built from source

**Additional context**
Using the `mas open appstore` command behaves the same.

Note that clicking a link such as [macappstore://](macappstore://) (or running the `open macappstore://` command in Terminal) does the same thing. This seems to be the current behavior of the MAS GUI app on Mojave. Perhaps there is a specific host or path that needs to be added to the URL to indicate the desired landing page and prevent this message.

Also, the [macappstore://showUpdatesPage](macappstore://showUpdatesPage) URL (discovered on an [OS X Daily post](http://osxdaily.com/2011/12/13/launch-mac-app-store-updates-url/)) successfully opens the MAS GUI app to the "⬇ Updates" tab without error.

**Comment by rgoldberg** [comment]
@phatblat @tonyarnold 

All of the left sidebar tabs can be opened with URLs like:

```
macappstore://?action=<lower case tab name>
macappstore://?action=discover
macappstore://?action=updates
…
```

It would be nice to find some URL that opens the App Store to the most recent page without any spurious dialogs, but I haven't found it yet.

We could default no argument to open a specific tab (I'd prefer Updates, but maybe others prefer Discover)/

To choose a specific tab, which of the following cli options do you prefer for the example of updates:

```
mas open --updates

mas open --tab updates
mas open --tab-updates
mas open --tab:updates

mas open --action updates
mas open --action-updates
mas open --action:updates
…
```

Also, we could either limit the options to the existing list of tabs (which would require updating whenever tabs are changed), or we could allow any ad hoc value. Any value that is unrecognized just opens the App Store to the most recent tab & outputs the same spurious error dialog. If we allow ad hoc values, I would go for an option syntax that begins with `--action`: 

- we might add other options to this command later; they could clash with an action/tab name
- actions might exist that are not tab names, so the broader naming would be correct in more situations

I can easily implement whatever syntax & behavior you prefer.
