### ISSUE TITLE
zsh tab completion

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#222]
Completion of `mas` command arguments for zsh users. Bash (#157) and Fish Shell (#214) are currently supported.

## References

- zsh [Completion System](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Completion-System) (aka `compsys`)
- Homebrew [`Formula#zsh_completion`](https://www.rubydoc.info/github/Homebrew/brew/Formula:zsh_completion)
   - our [formula](https://github.com/mas-cli/mas/blob/master/Homebrew/mas.rb#L32-L33)

Do any zsh users want to contribute this?

**Comment by rgoldberg** [comment]
Closing in favor of #678
