### ISSUE TITLE
Conflict with another `trash`

### ISSUE THREAD

**Issue by kud** [mas-cli/mas#223]
Hello,

It's not a bug but not a feature request too. It's just a problem I've got.

mas installs the command "trash" http://hasseg.org/trash/ which comes in conflict with another command I've installed https://github.com/sindresorhus/trash

Maybe mas should check first if a trash command already exists? the problem is that the api of the other trash cmd could be different.

I don't know how to handle this to be fair.

Any idea?

Thank you. :)

**Comment by phatblat** [comment]
What version of `mas` are you using? We had other issues with the external trash command, so I removed that dependency in [1.6.2](https://github.com/mas-cli/mas/releases/tag/v1.6.2).

**Comment by kud** [comment]
`1.6.2` :)

but as I installed a previous mas version, trash was already installed as dep.

I just had to `brew uninstall trash` and now `brew doctor` is fine. Thank you. :)

**Comment by phatblat** [comment]
Awesome, glad to hear it!
