### ISSUE TITLE
Application names missing after upgrading to 10.14.4 and latest Xcode Tools

### ISSUE THREAD

**Issue by jamesdh** [mas-cli/mas#226]
**Describe the bug**
Just upgraded to latest OSX and after generating a new Brewfile, this is what I see: 
```
mas "", id: 568494494
mas "", id: 915542151
mas "", id: 926036361
etc...
```

So I tried `mas list` from CLI and this is what I get:
```
450063525  (2.0)
915542151  (1.4.5)
926036361  (4.4.0)
etc...
```

This probably isn't going to be easily reproducible for others, unless this actually has nothing to do with the upgrade.

**To Reproduce**
1. Install latest MAS w/ 10.14.3
2. Upgrade to 10.14.4
3. Try retrieving installed apps

**Expected behavior**
App names shown in `mas list` or generated Brewfiles

**Actual behavior**
App name is missing, although version info is shown in `las list`

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - mas version: 1.6.2
 - macOS version: 10.14.4
 - How did you install mas? brew

**Additional context**
Will add more as I figure out what on earth is going on here...

**Comment by jamesdh** [comment]
Oddly enough, `mas search` does show app names correctly. 

E.g. `mas search Xcode` returns...
```
   497799835  Xcode                                                                (10.2)
  1183412116  Swiftify for Xcode                                                   (4.6.1)
  1163893338  App School for Xcode and  iOS 10 Development Free                    (1.0)
  etc...
```

**Comment by phatblat** [comment]
Confirmed in mas 1.6.2 on macOS 10.14.4.

```
 brew bundle dump --force; tail Brewfile
mas "", id: 975937182
mas "", id: 889428659
mas "", id: 1091189122
mas "", id: 915041082
mas "", id: 1447415753
mas "", id: 549083868
mas "", id: 1246284741
mas "", id: 803453959
mas "", id: 924726344
mas "", id: 904280696
```

**Comment by phatblat** [comment]
`mas list` is the root issue here as `brew bundle dump` [depends](https://github.com/Homebrew/homebrew-bundle/blob/f785096b5a3a1a931d79aa0c34540be93801f257/lib/bundle/mac_app_store_dumper.rb#L15) on it.

**Comment by phatblat** [comment]
Debugging the `list` command in Xcode on both recent patch versions of Mojave show that something is up with the [`CKSoftwareProduct.appName`](https://github.com/mas-cli/mas/blob/master/PrivateFrameworks/StoreFoundation/CKSoftwareProduct.h#L85) property.

## macOS 10.14.3
```
(lldb) po product.appName
"Things3"

(lldb) po product
<CKSoftwareProduct: 0x101687e00>: (com.culturedcode.ThingsMac, 3.8.4, 904280696:830763987 VPP:NO md:0x0 /Applications/Things3.app) 

904280696 Things3 (3.8.4)
```

## macOS 10.14.4
```
(lldb) po product.appName
""

(lldb) po product
<CKSoftwareProduct: 0x101113b30>: (com.culturedcode.ThingsMac, 3.8.4, 904280696:830763987 VPP:NO md:0x0 /Applications/Things3.app) 

904280696  (3.8.4)
```

**Comment by phatblat** [comment]
So, this doesn't look like a macOS API change, just that the app name isn't there. I have a potential workaround to fall back to displaying the `bundleIdentifier` when the `appName` is blank.

```
$ mas list
904280696 com.culturedcode.ThingsMac (3.8.4)
675248567 com.apple.InstallAssistant.Mavericks (1.3.46)
1040160984 com.swiftClean (2.0)
918858936 it.bloop.airmail2 (3.6.58)
1333542190 com.agilebits.onepassword7 (7.2.5)
418412301 com.codingwithlove.clean (1.0.3)
413857545 com.mizage.Divvy (1.5.1)
890031187 com.brettterpstra.marked2 (2.5.31)
1419224245 com.codebasesaga.macOS.Canopy (1.1.2)
1384080005 com.tapbots.Tweetbot3Mac (3.2.2)
975937182 com.flexibits.fantastical2.mac (2.5.7)
889428659 com.iconfactory.mac.xScope (4.3.3)
1091189122 net.shinyfrog.bear (1.6.10)
915041082 com.apple.InstallAssistant.Yosemite (1.6.43)
1447415753 com.steamclock.quests (1.0.16)
549083868 de.milchimgemuesefach.Display-Menu (2.2.3)
1246284741 com.apple.InstallAssistant.HighSierra (13.6.02)
803453959 com.tinyspeck.slackmacgap (3.3.8)
924726344 com.junecloud.mac.Deliveries (3.1.1)
873245660 com.ddeville.spillo (2.0)
```

It's not pretty, but better than nothing. Let me know what you think of this and I'll keep digging to see if I can find the app name somewhere else.

**Comment by jamesdh** [comment]
@phatblat works for me. For me it's really just for reference when reviewing the Brewfile and removing items I may not want. As long as there is something there so I know what app an identifier maps to, I'm good 👍

**Comment by phatblat** [comment]
OK, I'm moving forward with the fix in #228. Here is how a Brewfile will look on 10.14.4:

```
...
cask "zeplin"
cask "peripheryapp/periphery/periphery"
mas "com.agilebits.onepassword7", id: 1333542190
mas "com.apple.InstallAssistant.HighSierra", id: 1246284741
mas "com.apple.InstallAssistant.Mavericks", id: 675248567
mas "com.apple.InstallAssistant.Yosemite", id: 915041082
mas "com.brettterpstra.marked2", id: 890031187
mas "com.codebasesaga.macOS.Canopy", id: 1419224245
mas "com.codingwithlove.clean", id: 418412301
mas "com.culturedcode.ThingsMac", id: 904280696
mas "com.ddeville.spillo", id: 873245660
mas "com.flexibits.fantastical2.mac", id: 975937182
mas "com.iconfactory.mac.xScope", id: 889428659
mas "com.junecloud.mac.Deliveries", id: 924726344
mas "com.mizage.Divvy", id: 413857545
mas "com.steamclock.quests", id: 1447415753
mas "com.swiftClean", id: 1040160984
mas "com.tapbots.Tweetbot3Mac", id: 1384080005
mas "com.tinyspeck.slackmacgap", id: 803453959
mas "de.milchimgemuesefach.Display-Menu", id: 549083868
mas "it.bloop.airmail2", id: 918858936
mas "net.shinyfrog.bear", id: 1091189122
```

It's nice that brew-bundle sorts the app "names" alphabetically, causing multiple apps from the same vendor to be grouped (see `com.apple`) due to the common prefix in their bundle identifiers.

**Comment by phatblat** [comment]
One more test, showing how `brew bundle install` is now printing names instead of a bunch of confusing lines 
 with only "Using" on them.

```
...
Using zeplin
Using peripheryapp/periphery/periphery
Using com.agilebits.onepassword7
Using com.apple.InstallAssistant.HighSierra
Using com.apple.InstallAssistant.Mavericks
Using com.apple.InstallAssistant.Yosemite
Using com.brettterpstra.marked2
Using com.codebasesaga.macOS.Canopy
Using com.codingwithlove.clean
Using com.culturedcode.ThingsMac
Using com.ddeville.spillo
Using com.flexibits.fantastical2.mac
Using com.iconfactory.mac.xScope
Using com.junecloud.mac.Deliveries
Using com.mizage.Divvy
Using com.steamclock.quests
Using com.swiftClean
Using com.tapbots.Tweetbot3Mac
Using com.tinyspeck.slackmacgap
Using de.milchimgemuesefach.Display-Menu
Using it.bloop.airmail2
Using net.shinyfrog.bear
Homebrew Bundle complete! 236 Brewfile dependencies now installed.
```

**Comment by jamesdh** [comment]
> It's nice that brew-bundle sorts the app "names" alphabetically, causing multiple apps from the same vendor to be grouped (see com.apple) due to the common prefix in their bundle identifiers.

I can't unsee this. Now I wish `brew bundle` used the same convention for everything else!

Thanks for getting this in so quick @phatblat!

**Comment by phatblat** [comment]
BTW, 1.6.3is out now on brew
