### ISSUE TITLE
Stop being so awesome. 

### ISSUE THREAD

**Issue by jamesdh** [mas-cli/mas#227]
**Describe the bug**
Seriously, you guys revived what seemed to be a dying/dead project. Works like a charm now. Super grateful for your efforts! Keep it going!

**To Reproduce**
1. `brew install mas`
2. Enjoy

**Expected behavior**
Useful utility

**Actual behavior**
Awesomely useful utility

**Additional context**
Duplicates #11 
Relates to #110

**Comment by phatblat** [comment]
🤗 Thanks for the feedback! I couldn’t let this project die and am glad to help out. It’s mostly just me working on mas now, but always open to outside contributors or even bringing on new core contributors.

**Comment by davedelong** [comment]
If the request is to _stop_ being awesome, I recommend closing this issue as "Won't Fix" 👍

**Comment by jamesdh** [comment]
Closing per @davedelong's recomendation!
