### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject

### ISSUE THREAD

**Issue by benbalter** [mas-cli/mas#232]
Thanks for a great project! :tada:

Starting today, running `mas list` I get the following:

```
dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject
  Referenced from: /usr/local/Cellar/mas/1.6.3/bin/../Frameworks/MasKit.framework/Versions/Current/Frameworks/Commandant.framework/Commandant
  Expected in: /usr/lib/swift/libswiftCore.dylib
 in /usr/local/Cellar/mas/1.6.3/bin/../Frameworks/MasKit.framework/Versions/Current/Frameworks/Commandant.framework/Commandant
[1]    83692 abort      mas list
```

Versions:

* Mas version 1.6.3 (via homebrew)
* OS X Version 10.14.4 Beta (18E174f) <-- I suspect this may be the culprit as I think an automatic update was installed overnight

**Comment by phatblat** [comment]
Looks like you're running on the [initial beta of 10.14.4](https://github.com/phatblat/ApplePlatformVersions/blob/master/macOS.md#10144), which came out a couple months ago. The final release of 10.14.1 is out now. Could you update to that and see if `mas` still blows up?

FYI, once you install the macOS Developer Beta Access Utility, you can opt out by clicking the little "Details..." button on the Software Update pane.

![Screen Shot 2019-04-05 at 5 37 26 PM](https://user-images.githubusercontent.com/28851/55661524-7f761980-57c9-11e9-8033-b72a952a7009.png)

**Comment by phatblat** [comment]
Saw a similar error on my build server running macOS 10.14.3 (18D109).

```
carthage --version
dyld: Symbol not found: _$s11SubSequenceSlTl
  Referenced from: /usr/local/bin/carthage
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/carthage
fish: 'carthage --version' terminated by signal SIGABRT (Abort)
```

The above issue with carthage is Carthage/Carthage#2757 and mas may have a similar issue with the bundled Swift dylibs (it's packaged very similar to Carthage).

**Comment by phatblat** [comment]
@benbalter if updating macOS doesn't resolve this issue, could you try removing `mas` via brew and installing from our `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)?

**Comment by benbalter** [comment]
Very odd. I have no idea why it wasn't auto-updating. Updated and working as expected. Thanks for the quick and thoughtful reply, and for contributing such great software. :tada:
