### ISSUE TITLE
Insufficient permissions for installation

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#238]
如题，请问应该怎么做？

**Comment by phatblat** [comment]
I don't know Chinese, but Google translate tells me your issue title translates to "Installation display permission is not enough". Are you using the `mas install` command? The user you are logged in as will need to be an admin since apps are installed into the `/Applications` folder.

**Comment by greatplum** [comment]
非常感谢您，只需要在使用`mas`时加上`sudo`就好了

**Comment by greatplum** [comment]
但是它`install`时显示`Warning:  is already installed`
