### ISSUE TITLE
Doesn't work with System Updates

### ISSUE THREAD

**Issue by JayBrown** [mas-cli/mas#24]
I also had the problem described elsewhere: needed to run `mas signout` first in order to do a correct `mas signin`. (Also did a reboot beforehand to be sure, and also set to "save password" for free downloads in the App Store PrefPane.)

Now there's a different problem: updates are available at the MAS, but `mas outdated` is showing nothing at all; and the "outdated" option is the primary reason for me to use mas.

System: 10.11.4
Installed with: `brew install argon/mas/mas`

**Comment by JayBrown** [comment]
Tried uninstalling and re-installing, now with `brew install mas`, but still no output with `mas outdated`.

**Comment by JayBrown** [comment]
Problem of missing stdout might have been that the available update was not a regular MAS application update, but an OS X system update (Camera Raw). Will examine this further and report back.

**Comment by argon** [comment]
That would be the issue. Mas will only work with Application updates. System updates are handled through the `softwareupdate` utility

—A
