### ISSUE TITLE
🐛 [BUG] Outdated and Upgrade does not work on macOS Catalina

### ISSUE THREAD

**Issue by ruchern** [mas-cli/mas#244]
## Your Environment

- `mas version`: 1.6.3
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): macOS 10.15 (19A583)

### mas Install Method

- [X] `brew install mas` (homebrew-core)
- [X] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [ ] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [ ] Built from source
   - Fork/branch: ? (e.g. mas-cli/master)
   - Xcode version: 11.1

## Describe the Bug

> A clear and concise description of what the bug is.

Mas is not doing anything on macOS Catalina. 

- `mas outdated` does not detect any outdated apps despite actually having apps with updates.
- `mas upgrade` does nothing.

## To Reproduce

Steps to reproduce the behaviour:

1. Open terminal
2. Type `mas outdated` 
3. Type `mas upgrade`

## Expected Behavior

> A clear and concise description of what you expected to happen.

- `mas outdated` to show outdated apps when the apps in the App Store has updates.
- `mas upgrade` to upgrade outdated apps.

## Actual Behavior

> A clear and concise description of what actually happened.

- `mas outdated` - no apps are outdated when there are apps with updates in the App Store
- `mas upgrade` -  does nothing; says all apps are up to date

**Comment by phatblat** [comment]
Thanks for the bug report! This broke a while ago in #111

**Comment by ruchern** [comment]
@phatblat thanks for the heads up.

**Comment by ruchern** [comment]
Should I go ahead to close this or leave it as a tracking for macOS Catalina?

@phatblat

**Comment by ruchern** [comment]
Closing till macOS Catalina is officially released.

**Comment by ruchern** [comment]
Re-opened and updated description accordingly.

**Comment by yalefox** [comment]
This is broken again, unfortunately. With the same steps as outlined above.
