### ISSUE TITLE
Apple Remote Desktop compatibility?

### ISSUE THREAD

**Issue by bkrivelow** [mas-cli/mas#25]
Just wondering if this is compatible with Apple Remote Desktop? I can't seem to get the mas commands to work properly when I push a unix command via ARD.

**Comment by argon** [comment]
Unfortunately I haven't got any experience with ARD so I don't have an answer at this point. I think some other people have tried so perhaps they will have some comments.

**Comment by bkrivelow** [comment]
Thanks for the quick response. I will post what error I receive and hopefully someone knows what I have to do. Would really like to get this up and running. We manage over 100 Imacs and there's no easy way to just update the App store stuff without going into the computers individually.

**Comment by bkrivelow** [comment]
![screen shot 2016-04-26 at 10 11 55 am](https://cloud.githubusercontent.com/assets/18681840/14821126/8c065fd8-0b97-11e6-9385-18b804fc97b5.png)

**Comment by timsutton** [comment]
You need to specify a full path to `mas` since in this case the environment doing the "Send UNIX Command" doesn't include `/usr/local/bin` in its default `PATH`. So use `/usr/local/bin/mas`.

**Comment by bkrivelow** [comment]
That worked! now one other thing. I am trying to run the signin command but i keep getting error(7)null. Any idea what that might be?

Thanks again!

**Comment by argon** [comment]
If the `7` is coming from the app that is the `AlreadySignedIn` error code: https://github.com/argon/mas/blob/master/mas-cli/Error.swift#L21

**Comment by bkrivelow** [comment]
Hi, I don't think I am already signed in though. When I run the mas install command I can see on my test computer that it brings up the Apple ID sign in.

**Comment by argon** [comment]
If you open the App Store on the test machine and check the `Store` menu you will probably find you are signed in. Sometimes install will prompt for password if you signed in a long time ago.

If you run `mas signout` followed by `mas signin` then try to install does it still bring up the prompt?

**Comment by bkrivelow** [comment]
Yes the sign in to download from app store prompt still comes up even after doing the signout and signin command. I do notice though that I do not get the signing into app store line in terminal but it doesnt kick back an error.

**Comment by argon** [comment]
If you're still having this problem could you please try with a newer version?
