### ISSUE TITLE
iTunes App Store integration

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#251]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out a way to automate the download process of iOS Apps over iTunes/AppStore on macOS. I am using iTunes 12.6.5 (which still supports the AppStore)

**Describe the solution you'd like**
Is there a Chance to expand your system to the iOS AppStore, so that it will check the standard folder path ~/Music/iTunes/Media/Mobile\Applications/ and every app from there will get checked against new versions.

**Describe alternatives you've considered**
If there is no way to integrate it in this tool, is there a way to check specific apps and download them directly over the actual link itself?

**Additional context**
If there is no chance to integrate this huge feature, I still appreciate your hard and awesome work you are doing with mas itself!

**Comment by phatblat** [comment]
This is a cool idea, but not one that I have much information about. There are [short URLs](https://developer.apple.com/library/archive/qa/qa1633/_index.html) for deep linking into the App Store, but with this feature being removed from the latest version of iTunes, I expect these URLs would just drop you on a web page where you can install the app.

You can still [install the iTunes](https://www.cnet.com/how-to/still-want-to-install-ios-apps-with-itunes-youre-in-luck/) app, but as Apple has been moving away from using iTunes to manage iOS devices it seems that tapping into the [Apple Configurator app](https://support.apple.com/guide/apple-configurator-2/add-apps-to-a-device-cad4cd08c03/2.10/mac/10.14) might be more productive and future-proof.

The hardest part about all of this is that Apple doesn't provide public (supported) APIs for calling from a custom app. This makes keeping a tool like `mas` working very difficult and I'd prefer not to add too much scope to it like managing apps for a different platform.

However, if someone like yourself is interested in building a separate tool for downloading iOS apps, there are parts of this project that could be reused. The current search functionality uses the [iTunes Search](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/index.html) (web) API as I haven't figured out if there is a native API for this functionality. iOS apps can be found by simply changing a few parameters in the [search URL](https://github.com/mas-cli/mas/blob/master/MasKit/Controllers/StoreSearch.swift#L32).

Neat idea, but I'm going to pass on including this in mas.
