### ISSUE TITLE
Add `archive`

### ISSUE THREAD

**Issue by haakonstorm** [mas-cli/mas#253]
**Is your feature request related to a problem? Please describe.**

- macOS is parsing every .App on local file systems and by default auto-enables every apps `document provider` capabilities and adding all "actions" to the respective `share sheets` throughout the interface. 

- Anyone with an above-average collection of software tools, know how fast the "open with..." system dialog list grows ... sometimes returning *every* .app able to provide service for that particular file type. Right-clicked a `.txt` on Catalina lately?   
- In parallel, the "share..." sheet dialog also quicky ridiculou-lizes itself - here coincidentally illustrated via two screen shots superimposed on top of a funny I made with my cat flying through the universe: 

![2019-11-24_02-31-57](https://user-images.githubusercontent.com/193781/69488234-d880e380-0e66-11ea-827a-9087f9cb7a7d.png)

- `AppDelete`  by Reggie Ashworth (RIP - development taken over by a friend of the family) has a feature called  "Archive":

![2019-11-24_02-55-27](https://user-images.githubusercontent.com/193781/69488232-d28b0280-0e66-11ea-9021-60f4e575003e.png)

**Describe the solution you'd like**
- I'd like for `mas` - in addition to ` install`  / ` uninstall` - also gain "archive" and "restore from archive" features. 
- When you archive an app with 'AppDelete, it copies the entire .App bundle to a ZIP (or tarball) along with all the preferences and supporting data, then deletes said files - effectively disabling the apps `document provider` capabilities and also the `share sheet actions`. 

In addition to enhancing your the macintosh operators mental well being, you also get a simple way to have a rudimentary backup of the particular version of the app as well as a configuration set known to work on that version. As you are aware Apple restricts access to old versions of apps, and previously having a previous version *including its config* has saved my bacon couple of times. Easier, way faster and less error-prone than restoring from backup.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered:

Using `git LFS` and a dotfiles *bare repository* setup e.g. on `github` is a more complete solution to the above problem. I will argue however that this is complex for many to set up and keep maintained. In addition, having *both* mechanisms in place has no negative effects and can be a clever move for fun and profit anyway.

**Additional context**
Thoughts from the top of my mind:

- `mas archive 1295203466` → move app and all its files to a zip in `/Apps` or `~/Apps`
- `mas archive --tar 1295203466` → same, with tarball
- `mas backup [--tar] 1295203466` → create [zip|tar] but keep application untouched 

Thank you for your time and your awesome success with `mas` cli. **Keep up the great work!**

Best regards from Oslo, Norway
storm

**Comment by phatblat** [comment]
This is a good idea. I've been having some trouble with the `uninstall` command (see #216) and side-stepping the app removal might be a lot simpler.
