### ISSUE TITLE
🐛 [BUG] Linuxbrew Error: undefined method `installed?' for OS::Mac::Xcode:Module

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#259]
🆕 Installing: mas
Error: undefined method `installed?' for OS::Mac::Xcode:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting

add to formula
```
  depends_on :macos
```

**Comment by andrewcrook** [comment]
Does this need to be raise with Homebrew's repository?

**Comment by phatblat** [comment]
No, just something to configure on the formula to mark it as not compatible with Linuxbrew.

**Comment by chris-araman** [comment]
Looks like this was resolved with https://github.com/mas-cli/mas/commit/7e3c03b43d3daf2e44664f343f77e1edaf5c58ab#diff-c28d89b8f0ee86b84e2ea6653986e5a5ae04a22d3a603936351d5ccdb275ef18R17.

@phatblat, can this be closed?

**Comment by chris-araman** [comment]
It looks like this was resolved [here](https://github.com/mas-cli/mas/commit/7e3c03b43d3daf2e44664f343f77e1edaf5c58ab#diff-c28d89b8f0ee86b84e2ea6653986e5a5ae04a22d3a603936351d5ccdb275ef18R17).

@phatblat, can this be closed? If not, how do I reproduce this issue?
