### ISSUE TITLE
Add an 'info' command

### ISSUE THREAD

**Issue by 0xdevalias** [mas-cli/mas#26]
Not sure if it's possible, but it would be awesome to have a `mas info` type command to get more details about the package/id. (similar to homebrew)

```
⇒  brew info mas
mas: stable 1.2.0 (bottled)
Mac App Store command-line interface
https://github.com/argon/mas
/usr/local/Cellar/mas/1.2.0 (4 files, 6.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mas.rb
```

```
mas info 123456
mas info Some App Name Here
```

If possible, maybe the app name, short description, link to the full appstore page, and whether it's installed or not?

Edit: Looks like the [itunes lookup api](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/#lookup) would provide the required bits of info for this:

Eg. https://itunes.apple.com/lookup?id=886106985

**Useful Sounding Keys:** kind, features, supportedDevices (filter for OSX), advisories (maybe), fileSizeBytes, averageUserRatingForCurrentVersion, userRatingCountForCurrentVersion, trackContentRating, trackCensoredName, trackViewUrl, contentAdvisoryRating, minimumOsVersion, formattedPrice, wrapperType, version, currency, artistId, artistName, genres, price, description, trackName, trackId, bundleId, releaseDate, primaryGenreName, currentVersionReleaseDate, releaseNotes, sellerName, averageUserRating, userRatingCount

**Other Keys:** screenshotUrls, ipadScreenshotUrls, appletvScreenshotUrls, artworkUrl512, artistViewUrl, artworkUrl60, artworkUrl100, isGameCenterEnabled, languageCodesISO2A, isVppDeviceBasedLicensingEnabled,  primaryGenreId, genreIds

As one possible example:

```
trackCensoredName: version [currency price or formattedPrice] (genres)
By artistName(or sellerName)
description(limit length to something reasonable)...
Current Rating: averageUserRatingForCurrentVersion, Overall Rating: averageUserRating
sellerUrl
Released: currentVersionReleaseDate
Min OS: minimumOsVersion(could check this against system)
Size: fileSizeBytes(calculated to a pretty value)
From: trackViewUrl
```

**Comment by pascalandermatt** [comment]
> If possible, maybe the app name, short description, link to the full appstore page, and whether it's installed or not?

Keynote: 409183694

So the Appstore link would be
macappstores://itunes.apple.com/app/id409183694

It is may possible to read the description and app name from the website
https://itunes.apple.com/app/id409183694

**Comment by pascalandermatt** [comment]
>Eg. https://itunes.apple.com/lookup?id=886106985

https://itunes.apple.com/app/id409183694 and read the information from the page

**Comment by phatblat** [comment]
This has been added in #55
