### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by 85u2e8** [mas-cli/mas#262]
## Your Environment

- `mas version`:
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.1...

### mas Install Method

- [] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
   - Fork/branch: ? (e.g. mas-cli/master)
   - Xcode version: 10.?

## Describe the Bug

> A clear and concise description of what the bug is.

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected Behavior

> A clear and concise description of what you expected to happen.

## Actual Behavior

> A clear and concise description of what actually happened.

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```
$ mas command
...
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

**Comment by phatblat** [comment]
This issue doesn't contain any details. Please open a new issue and fill out the template if you want to report something or ask for a feature.
