### ISSUE TITLE
No search results for Dato

### ISSUE THREAD

**Issue by NuroDev** [mas-cli/mas#265]
## Your Environment

- `mas version`: `1.6.3`
- macOS version: `10.1.15.3`

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [ ] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [ ] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [ ] Built from source
   - Fork/branch: ? (e.g. mas-cli/master)
   - Xcode version: 10.?

## Describe the Bug

> Similar to a small selection of other apps, search results for [Dato](https://sindresorhus.com/dato) do not list the app.

## To Reproduce

1. Run `mas search Dato`
2. See results list

## Expected Behavior

> Return the app ID (`1234567890  Dato (1.10.2)`)

## Actual Behavior

> A clear and concise description of what actually happened.

## Screenshots, Terminal Output

<img width="612" alt="Screenshot 2020-04-14 at 7 17 31 pm" src="https://user-images.githubusercontent.com/4991309/79260213-d0f9bf80-7e85-11ea-8182-d24981f46dda.png">

```
$ mas search dato
1188641845	SurfPro VPN - Best VPN to Protect Privacy and Data  (1.1)
1081798042	SimpleumSafe - Encryption							(2.8.1)
1086779260	Universal Database									(2.01.04)
```

**Comment by phatblat** [comment]
Fixed in #269
