### ISSUE TITLE
Include binaries with the new releases 

### ISSUE THREAD

**Issue by acrostich** [mas-cli/mas#276]
For v1.6.4 and v1.7.0, the assets on https://github.com/mas-cli/mas/releases do not include the binary.

It would be helpful if binaries where posted to the Release page with each new version.

I am not using Homebrew, but Macports, an alternative would be to support the build of mas-cli with Macports as well as with Homebrew.

**Comment by phatblat** [comment]
Resolved now.

The [`package`](https://github.com/mas-cli/mas/blob/master/script/package) script has been misbehaving, but the macOS 10.15.5 update yesterday seems tohave fixed it.
