### ISSUE TITLE
🐛 [BUG] `mas search Amphetamine` not returning results

### ISSUE THREAD

**Issue by jakewilliami** [mas-cli/mas#279]
## Your Environment

- `mas version`: 1.6.3
- macOS version: 10.14.6

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
   - Fork/branch: ? (e.g. mas-cli/master)
   - Xcode version: 10.?

## Describe the Bug

The application "Amphetamine" is not showing up when searched for using `mas`, yet is installed:
```
$ mas list
1278508951 Trello (2.11.4)
937984704 Amphetamine (5.0.1)
409201541 Pages (8.2.1)
409203825 Numbers (6.2.1)
```

## To Reproduce

1. Run `mas search Amphetamine` or (in my above example, to be precise) `mas search $(mas list | awk 'NR==2{print $2}')`

## Expected Behavior

To download Amphetamine.

## Actual Behavior

See output: 
    ```
    No results found
    Error: No results found
    ```

## Additional Context

The fact that I have it downloaded implies it has worked previously.

**Comment by florianrusch** [comment]
For me it helped to upgrade mas to 1.7.0:
```
$ mas version
1.7.0
$ mas search Amphetamine
   937984704  Amphetamine                   (5.0.2)
   946798523  AntiSleep - Keep System Awake (2.16.2)
  1362171212  Caffeinated - Anti Sleep App  (1.18)
  1263070803  Lungo                         (1.7.0)
```

**Comment by jakewilliami** [comment]
Yep, that was it.  Thank you @florianrusch.
