### ISSUE TITLE
🐛 [BUG] `mas search things` fails with "Error: Unable to parse response JSON"

### ISSUE THREAD

**Issue by dwlf** [mas-cli/mas#284]
## Your Environment
1.7.0
      System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0
      Time since boot: 7:21

### mas Install Method

brew install mas

## Describe the Bug

`mas search things fails` with
Error: Unable to parse response JSON

### Background

I install Cultured Code Things using mas. I use a `mas search` to find the thingsProductID.

## To Reproduce

% brew install mas
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Casks
ipe                                                             ipepresenter

Warning: mas 1.7.0 is already installed and up-to-date

lll@MacBook-Pro ~ % mas version      
1.7.0
lll@MacBook-Pro ~ % mas search things
Error: Unable to parse response JSON
lll@MacBook-Pro ~ % mas search thi   
Error: Unable to parse response JSON
lll@MacBook-Pro ~ % mas search th    
   673308830  TH Templates for Pages Docs Lt                                 (2.6.1)
   726881569  TH - Themes for Keynote Presentations Lite                     (2.0)
...

**Comment by phatblat** [comment]
Thanks for the report. I've seen this with a few app titles but some others (airmail) are working.

**Comment by phatblat** [comment]
## Working

- airmail
- tweetbot

## Fail with JSON Error

- things
- bear

**Comment by yoyoys** [comment]
`line` also give this error

**Comment by phatblat** [comment]
Looks like some bad data coming from the iTunes Affiliate search API, missing values for:

- `fileSizeBytes`
- `formattedPrice`
- `price` (normally present, but "Free" when no cost)

This can be fixed with some extra logic to handle these missing values.

**Comment by chuckhendo** [comment]
@phatblat FYI, It looks like the items that are missing those properties are games in Apple Arcade. For example, when I search for 'things', the item missing those properties is 'Things That Go Bump,' which is available on Apple Arcade.

**Comment by phatblat** [comment]
Great observation @chuckhendo! Since Apple Arcade is a somewhat newer concept and you don't "pay" for those titles, it makes sense why the `price` value is missing. I've got a fix in the works, just need to do a little more testing before I put it out in 1.7.1.

**Comment by phatblat** [comment]
Fixed in [1.7.1](https://github.com/mas-cli/mas/releases/tag/v1.7.1). Homebrew update pending, but the new version can be installed now via the .pkg installer attached to the release.
