### ISSUE TITLE
`lucky`: Install multiple apps

### ISSUE THREAD

**Issue by mariobrostech** [mas-cli/mas#287]
**Is your feature request related to a problem? Please describe.**
I currently use a script to deploy App Store apps with mas. When I run `mas install id1 id2 id3`, mas installs all 3 of the apps with their respective IDs. However, if I run `mas lucky app1 app2 app3`, I get an error saying `Unrecognized arguments: "app1" "app2" "app3"`
Why don't these commands work in a similar manner?

**Describe the solution you'd like**
I would like for mas to install every app written after the `mas lucky` command, just like it currently does with the `mas install` command.

**Describe alternatives you've considered**
I've considered just using the `mas install` command in my script, but it's too much work for me to get the IDs over 50 apps that are on my account (some of them are not installed at this time, so I can't list them with mas).

**Comment by zntfdr** [comment]
Duplicate of #168

**Comment by mariobrostech** [comment]
Sorry about that, I'll close this issue so you can work on it over there. Thanks!
