### ISSUE TITLE
Add already installed apps to mas?

### ISSUE THREAD

**Issue by ph55** [mas-cli/mas#288]
After installing mas, applications that were already installed manually via App Store don't appear when I run `mas list`.

* Is there any way to make mas "see" manually installed apps ?
* If I install app via mas and it was already installed manually, wouldn't it conflict ? 
* Should I uninstall manually installed app before installing it via mas ?

**Comment by phatblat** [comment]
What do you mean by "manually" installed? Did you use the "GET" or "cloud download" buttons in the App Store GUI? Or, did you download a package installer from the developer's website?

**Comment by ph55** [comment]
By manually I meant downloading from App Store GUI yes. I checked now and it works fine.
