### ISSUE TITLE
OS X 10.8 Compatibility

### ISSUE THREAD

**Issue by DolphinFlopFish** [mas-cli/mas#305]
## Your Environment

I haven't installed mas.

- macOS version 10.8.5

### mas Install Method

N/A

## Describe the Bug
The bug is compatibility issues with OS X 10.8.5.

I tried older versions of MAS and they did not work.

I tried Homebrew and MacPorts but they both did not work.

## To Reproduce

Get OS X 10.8.5
Install MAS

## Expected Behavior

MAS would auto-download an older version.

## Actual Behavior

I got an error:

```text
dyld: Library not loaded: /System/Library/PrivateFrameworks/StoreFoundation.framework/Versions/A/StoreFoundation
  Referenced from: /Users/myname/Downloads/mas
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by chris-araman** [comment]
@DolphinFlopFish, mas-cli currently requires macOS 10.11. If you or anybody else would like to implement support for older macOS releases, please consider opening a pull request.

**Comment by DolphinFlopFish** [comment]
don't worry i just got the package i was looking for on archive.org
