### ISSUE TITLE
How to grep the progress bar?

### ISSUE THREAD

**Issue by shoopdawoop** [mas-cli/mas#307]
A bit off topic perhaps, but I'll give it a shot:

I would like to run `mas install` in a shell script and report back when a download is finished and when it's successfully installed, but I cannot figure out how  to do the former.

I thought I'd try a simple `grep` on the output, but only a `mas install | grep "Installed"` works (on the final output after the whole process is finished), while a `mas install | grep "Installing"` does not work.

It seems that the the output of the progress bar

`################################################------------ 80.0% Installing`

never gets piped to grep and only the final results `==> Downloading` and `==> Installed` actually get passed.
Throwing a `| tee $somewhereelse` in there does not work, either.

How can this be done?

**Comment by shoopdawoop** [comment]
Nevermind, I found a way to work around this by temporarily sending `installd` to sleep until the download is finished.

I leave this open in case it is of interest to anyone as an actual feature request.

**Comment by phatblat** [comment]
The [`clearLine`](https://github.com/mas-cli/mas/blob/master/MasKit/Formatters/Utilities.swift#L44) called in [`PurchaseDownloadObserver`](https://github.com/mas-cli/mas/blob/master/MasKit/AppStore/PurchaseDownloadObserver.swift#L86) is probably what's fouling up that output. It's intended to rewrite the current line for an updating progress bar but messes up the final stdout that gets ends up in a command pipe.

Detection of stdout redirection and/or a way to force simpler, more reliable output would help.

**Comment by philsherry** [comment]
Came looking for information about this while staring at `Installing Xcode` in the output of a script that I've written, which uses `mas`. I've been staring at it for quite some time now.

**Comment by rgoldberg** [comment]
@shoopdawoop @philsherry
Would the simplest solution be to output a separate persistent `==> Downloaded <app name>` line after the refreshing download progress indicator line has disappeared, then a separate persistent `==> Installing <app name>` line above the refreshing install progress indicator line? The persistent output would thus be something like (I used a `mas upgrade` output rathe):

```
==> Downloading App Name
==> Downloaded App Name
==> Installing App Name
==> Installed App Name
```

Why do you want to grep for any of this? I've run `mas install` from scripts, where I can see all of the persistent output & both of the progress indicators as they progress (though the progress indicator lines eventually disappear). Why do you not want to see the progress indicators or other output? Do the progress indicator lines not refresh, but instead take up a different line per refresh (or something else)?

How does "sending installd to sleep until the download is finished" help?

**Comment by philsherry** [comment]
@rgoldberg It was 2 years ago but it was Xcode, which was notoriously large and cumbersome before they made it a bit more modular. 

Seeing output such as you suggested would always be a good start, yes.

**Comment by rgoldberg** [comment]
@philsherry Thanks for the info.

Are there any other problems that must be solved that aren't solved by the 2 extra persistent lines that I suggested? If I know additional problems, then I can devise & implement solutions to them.

I assume that grepping the progress indicators isn't actually necessary, it was just one proposed solution for which I've hopefully provided a better alternative.

Thanks for any more info you can provide.

**Comment by philsherry** [comment]
I can’t speak to the grepping issue, as that was OP so I’ll leave that for them. 

The only other gripe I can think of right now is newer versions *sometimes* disappearing from the Dock upon install… but sometimes, not. But I imagine that’s outside the remit of this particular Issue.

More than happy to help with further questions, testing, and so on. It’s a great tool and it’s good to know someone is back on it.

**Comment by rgoldberg** [comment]
@philsherry Thanks for the info.

I would assume that you meant disappearing from the Dock upon upgrade, not upon install, because how would it already be in the Dock if it weren't already installed? Or are you accidentally trying to install an app that was already installed?

Assuming you meant upgrade, have apps disappeared from the Dock when you've upgraded via the App Store GUI (instead of via `mas upgrade`)? If so, them it's an issue outside of mas (though mas could somehow increase the frequency). If not, then it's likely an mas problem.

If it seems like an mas problem to you, please open a new issue about it, and we can investigate it. It'll probably be a bit before we get to it, though, unless you or someone else pinpoint the problem, because of the large backlog of serious bugs & because it would require research into a whole new area, but it would be good to document as much as possible.

Thanks again.

**Comment by rgoldberg** [comment]
I looked at the code: it only outputs the progress indicator if stdout is a TTY. When you pipe, stdout is not a TTY.

The way to solve this is to do as I proposed in https://github.com/mas-cli/mas/issues/307#issuecomment-2351603462.

I'll work on this soon.
