### ISSUE TITLE
🐛 [BUG] mas list showing duplicated items

### ISSUE THREAD

**Issue by remy-tiitre** [mas-cli/mas#309]
## Your Environment

- mas version: 1.7.1
- macOS version 11.1 Big Sur

### mas Install Method

- brew install mas

## Describe the Bug

I actually used Ansible homebrew module first time when I installed mas, but then I did brew uninstall and manually installed brew install mas. Yet still has list shows duplicated rows like this:
409203825 Numbers (10.3.5)
409201541 Pages (10.3.5)
409183694 Keynote (10.3.8)
409183694 Keynote (10.3.8)
409183694 Keynote (10.3.8)
409203825 Numbers (10.3.5)
409201541 Pages (10.3.5)
409201541 Pages (10.3.5)
497799835 Xcode (12.3)
497799835 Xcode (12.3)
497799835 Xcode (12.3)
409203825 Numbers (10.3.5)

And I can't understand how to fix it. I have tried mas reset several times. Actually the problem started that on my clean Mac mas list already shows apps installed. So I downloaded manually from App Store and now I have duplicated items.

**Comment by remy-tiitre** [comment]
Newer mind. It seems that it managed to find apps from my backup.

**Comment by marvinosswald** [comment]
The same thing happend to me but with my second macos installation on another hdd, my issue being can i somehow reset this so i can install an app on my current macos installation ?

**Comment by chris-araman** [comment]
We could filter the list of "installed" apps to those under `/Applications/`. Do people expect `mas list` to show apps outside of that path?
