### ISSUE TITLE
Unable to parse response JSON (PDF Expert)

### ISSUE THREAD

**Issue by minuq** [mas-cli/mas#311]
## Your Environment

- `mas version`: 1.7.1
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): macOS 11.2 (20D5029f)

### mas Install Method

`brew install mas` (homebrew-core)

## Describe the Bug

`mas search` returns `Error: Unable to parse response JSON` when searching for PDF Expert by ID, but not by name. Search by ID works for other programs (tried 5 or so, all worked but PDF Expert).

## To Reproduce

`mas search "1055273043"`

## Expected Behavior

mas to show Information about the program identified by ID 1055273043

## Actual Behavior

mas erroring out, `Error: Unable to parse response JSON`

## Screenshots, Terminal Output

<img width="439" alt="image" src="https://user-images.githubusercontent.com/460656/103370116-44069d00-4acc-11eb-9755-522d7db2e387.png">

```
~ ❯ mas search "1055273043"                                      
Error: Unable to parse response JSON
~ ❯ mas search "PDF Expert" | grep "1055273043"                  
  1055273043  PDF Expert - Edit and Sign PDF (2.5.16)
~ ❯ mas search "1185380569"                                      
  1185380569  PDF Reader - Document Viewer (1.4.1)...
```

## Additional Context

Worked on previous mas versions. Probably related to #284

**Comment by minuq** [comment]
No idea what changed, but today it's working again after a week or so of failing.

```
 ~ ❯ mas search "1055273043"
  1055273043  PDF Expert - Edit and Sign PDF (2.5.16)
```

**Comment by phatblat** [comment]
@minuq the search command does an online request to the iTunes Search API and if there is a problem with the formatting of the JSON response it can cause this sort of error. Something probably changed in the data so I'm glad it's working now.
