### ISSUE TITLE
🐛 [DOCUMENTATION] Homebrew no longer installs mas

### ISSUE THREAD

**Issue by brandondrew** [mas-cli/mas#315]
## Your Environment

- `mas version`: N/A
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 

```
      System Version: macOS 11.0.1 (20B29)
      Kernel Version: Darwin 20.1.0
```

### mas Install Method

- [X] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
   - Fork/branch: ? (e.g. mas-cli/master)
   - Xcode version: 10.?

## Describe the Bug

> A clear and concise description of what the bug is.

The README says that we can install with `brew install mas` but this does not seem to work on any current Mac.  Instead this is returned:

```
% brew install mas
Error: mas: no bottle available!
You can try to install from source with:
  brew install --build-from-source mas
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

Of course the problem is with Homebrew, but this report is to notify you that your documentation appears to be mistaken, at least in the case of any Mac released in the last few months.  Since _to some extent_ I'm speculating that that is the determining factor, I don't feel confident to create a PR of a documentation change.  But if would be helpful if someone who does know exactly what is going on would make such a change. 

## To Reproduce

1. Buy a new Mac with Apple Silicon
2. Install Homebrew
3. Install Xcode
4. Open a terminal app
5. Enter `brew install mas`

## Expected Behavior

> A clear and concise description of what you expected to happen.

I expected mas to be installed.

## Actual Behavior

> A clear and concise description of what actually happened.

Instead I was told there were no bottles and I had to build from source, which was portrayed as a risky operation.

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```
$ mas command
...
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

**Comment by cho-m** [comment]
Homebrew does install `mas` on Intel Macs and via Rosetta 2 on M1 Macs.
There is a known issue #308 for ARM compilation which means `mas` cannot be installed natively on M1 yet. 

You can check whether a package is natively supported by looking for `arm64_big_sur` inside Formula's bottles.

`mas` bottles currently do not include ARM:
https://github.com/Homebrew/homebrew-core/blob/1520434ebf31c50ee1458725879570d1b50e384a/Formula/mas.rb#L10-L15

As opposite example, `bash` has ARM bottle:
https://github.com/Homebrew/homebrew-core/blob/1520434ebf31c50ee1458725879570d1b50e384a/Formula/bash.rb#L36-L38

It doesn't make sense to change the documentation when there is a way to to install `mas` via Homebrew on all Macs right now (Intel native, M1 Rosetta2) and there will be support for M1 Native once issue is fixed.

I am currently using an M1 Macbook Pro with dual Homebrew installs (Native in /opt/homebrew and an `arch -x86_64` version in /usr/local/) and have `mas` installed via Rosetta 2.

**Comment by phatblat** [comment]
@brandondrew are you on an M1 Mac?

mas 1.8.0 is available from the package installer attached to the release. Homebrew update is one its way in Homebrew/homebrew-core#71054

**Comment by brandondrew** [comment]
> @brandondrew are you on an M1 Mac?

Yes.

**Comment by brandondrew** [comment]
> It doesn't make sense to change the documentation when there is a way to to install `mas` via Homebrew on all Macs right now (Intel native, M1 Rosetta2) and there will be support for M1 Native once issue is fixed.

Updating documentation is quick and easy.  If the documentation is _currently_ saying something untrue, why would you not update it?  When the problem is fixed, you can change it back.  The purpose of the README is to have _current_ information, not information that _used to be_ correct and is _expected_ to one day become correct again.

Anyway, it is now working, so the point is no longer immediately applicable, but in the future _why would you not make a change to the documentation so that people know when something so important as installation is broken?_
