### ISSUE TITLE
Unable to install mas from brew on Mojave

### ISSUE THREAD

**Issue by ivanpesin** [mas-cli/mas#320]
## Your Environment

```console
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G8022
```

### mas Install Method

```console
$ brew install mas
mas: A full installation of Xcode.app 11.4 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode 11.4 cannot be installed on macOS 10.14.
You must upgrade your version of macOS.
Error: An unsatisfied requirement failed this build.
```

## Describe the Bug

Unable to install mas on MacOS X Mojave (10.14.6) due to failing dependency on Xcode 11.4 which is not available for Mojave.

## To Reproduce

- run `brew install mas` on OS X Mojave

## Expected Behavior

mas gets installed

## Actual Behavior

Installation fails with error.

## Screenshots, Terminal Output

```console
$ brew install mas
mas: A full installation of Xcode.app 11.4 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode 11.4 cannot be installed on macOS 10.14.
You must upgrade your version of macOS.
Error: An unsatisfied requirement failed this build.
```

**Comment by chris-araman** [comment]
@ivanpesin, please find instructions for installing on macOS 10.11 through 10.14 [here](https://github.com/mas-cli/mas/blob/master/README.md#%EF%B8%8F-older-macos-versions).
