### ISSUE TITLE
how can I uninstall it

### ISSUE THREAD

**Issue by yap241986** [mas-cli/mas#325]

**Comment by yap241986** [comment]
how con I uninstall it

**Comment by flaxel** [comment]
You can use one of the following commands:

```bash
brew uninstall mas
brew remove mas
```

**Comment by yap241986** [comment]
I don't install with brew, I install whit mad.pkg

**Comment by chris-araman** [comment]
@yap241986, where did you install `mad.pkg` from?

Many apps installed as .pkg files can be uninstalled by moving the installed application from `/Applications` to the Trash.

**Comment by chris-araman** [comment]
@yap241986, if you installed with `mas.pkg`, you can uninstall with:
```
sudo rm -rf /usr/local/Frameworks/MasKit.framework
sudo rm /usr/local/bin/mas
```
