### ISSUE TITLE
Stop tracking and ignore Carthage dir

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#340]
Splitting out from #334 

> Regarding Carthage, I'm not a fan of checking in copies of dependencies' source but I've left it that way ever since #169 because that was such a nightmare with me trying to get CocoaPods to work before @tonyarnold rescued the switch away from the latent CocoaSeeds. Curious about your thoughts on ignoring the Carthage/ dir since the scripts use the tool to bootstrap anyway.
> 
> I agree that the committed copies are awkward. I'm for removing them and adding them to .gitignore, or replacing them with submodules if Carthage supports that.

**Comment by chris-araman** [comment]
@phatblat, I can pick this up if you haven't started on it yet.

**Comment by phatblat** [comment]
Go for it 👍🏻

**Comment by chris-araman** [comment]
It sounds like `--use-submodules` is only worth the extra tracking if we intend to modify the dependencies in-place and push changes upstream. I don't know that that's likely, so I'll opt for the `.gitignore` solution instead.

**Comment by phatblat** [comment]
Yeah, pinning to a fork of a dependency is not ideal. I prefer to work with the maintainers and get fixes & features into the mainline.
