### ISSUE TITLE
♻️ mas should retry a download if it fails due to a network timeout

### ISSUE THREAD

**Issue by philsherry** [mas-cli/mas#344]
## Your Environment

- `mas version`: 1.8.1
- `Homebrew`: 3.0.10
- `Homebrew/homebrew-core` (git revision 72894f32b1; last commit 2021-03-31)
- `Homebrew/homebrew-cask` (git revision 4363b2e34d; last commit 2021-03-31)
- macOS version: 10.15.7 (19H524)

### `mas` Install Method

- [x] `brew install mas` (homebrew-core)
- [ ] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [ ] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [ ] Built from source
  - Fork/branch: ? (e.g. mas-cli/master)
  - Xcode version: 10.?

## Describe the Bug

When running `brew update`, I’m getting network timeouts from the App Store during the `mas` section of my `Brewfile`—all `brew` and `cask` dependencies install fine. Screenshots attached.

## To Reproduce

1. Run `brew update`.
1. Wait for `brew` and `cask` sections to complete.
1. Once `mas` section starts, pay attention.
1. See error.

## Expected Behavior

I expect Mac App Store installations to go smoothly.

## Actual Behavior

Mac App Store installations are interrupted by network timeouts.

## Screenshots, Terminal Output

```
$ brew update
  […]
  Upgrading 1 outdated application:
  Meeter (1.9.3)
  Error: Download request failed: The network connection was lost.
  Installing Meeter has failed!
```

![mas-fail-01](https://user-images.githubusercontent.com/272769/113155311-cd934b80-9230-11eb-8d4f-866579d82c80.png)
![mas-fail-02](https://user-images.githubusercontent.com/272769/113155318-cec47880-9230-11eb-8d38-bd6647d8fbde.png)

## Additional Context

This works fine on my 11.2.3 Macs, but this issue is on my work Mac. Until now, I've not had this issue on this Mac, but it's been several weeks since I ran updates.

**Comment by chris-araman** [comment]
@philsherry, is your work Mac configured to use any proxies? _System Preferences, Network, Advanced..., Proxies_ Do you see the same issue when no proxy is configured?

Does it run any particular antimalware, antivirus, or firewall software that may be intercepting network requests? Do you see the same issue when this software is disabled or removed (if possible)?

Does it connect to a VPN? Do you see the same issues when not connected to the VPN?

**Comment by chris-araman** [comment]
We might be able to wire up some retry logic here, in case of an unreliable network. I suspect the App Store app does something similar. We'd want to be sure that we only retry in case of a small set of specific errors. Many types of errors along this path mean retrying won't help.

**Comment by bric3** [comment]
Hi, I stumbled on this issue, while using mas directly `mas upgrade`, I see a popup "The network connection was lost".
However clicking the retry button don't fix the issue. It seems to happen for all apps that are tried to be downloaded, and I have to _cancel_ for each.


<img width="572" alt="image" src="https://user-images.githubusercontent.com/803621/131254979-faf2e384-3950-4251-9bc4-f63bf43e456d.png">


<img width="418" alt="image" src="https://user-images.githubusercontent.com/803621/131254880-eda13492-608d-4f4c-b1ec-b2285c2ff400.png">


The _app store_ does not list these updates though. But iterating each app on the app store, the _update_ button is there. I updated all of these, however mas still lists XCode. On the _App Store_, it is indicated that XCode 12.5 requires Big Sur and my current XCode version is 12.4, could it be related to this ?

MacOS Catalina (10.15.7)
mas version : 1.8.2
I am signed in my account in the _App Store_ app.

**Comment by chris-araman** [comment]
Thanks for the report, @bric3.

> I have to cancel for each.

Hrm... This should not be happening. We should instead fail fast after the first cancellation. However, that should be tracked as a separate issue. I've opened #408 for tracking.

> The app store does not list these updates though.

The App Store caches information about versions available in the App Store, and that cache is frequently found to be out-of-date. We've done some work in recent `mas` releases to avoid client-side caching, allowing `mas` to often see updates that have been published before the App Store app notices them (refreshing its cache).
