### ISSUE TITLE
Documentation: README has a broken link to softwareupdate(8) man page

### ISSUE THREAD

**Issue by bradtheappguy** [mas-cli/mas#347]
It seems that apple is no longer hosting the Darwin man pages on developer.apple.com.  These is some discussion about it here: https://stackoverflow.com/questions/53220058/darwin-reference-manual-pages-missing.

The readme file has a broken link to apple's old archive.  The link should probably either be removed or pointed to one of the several third-party sites hosting these man pages.

**Comment by chris-araman** [comment]
Thanks for reporting this, @bradtheappguy!
