### ISSUE TITLE
🍺 Issue building has package inside Homebrew's sandbox environment 

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#363]
## Your Environment

- `mas version`:
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.1...

### mas Install Method

- [] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [x] Built from source
  - Fork/branch: ? (e.g. mas-cli/master)
  - Xcode version: 10.?

## Describe the Bug

Working on updating the mas formula in homebred-core, but getting errors building the swift package.

```
↪ brew install --build-from-source mas
==> Cloning https://github.com/mas-cli/mas.git
Updating /Users/zoltar/Library/Caches/Homebrew/mas--git
==> Checking out tag v1.8.2
HEAD is now at c88a988 Merge pull request #361 from mas-cli/clean
HEAD is now at c88a988 Merge pull request #361 from mas-cli/clean
==> swift build --configuration release --arch arm64 --arch x86_64
Last 15 lines from /Users/zoltar/Library/Logs/Homebrew/mas/01.swift:
2021-05-06 21:33:21 -0600

swift build --configuration release --arch arm64 --arch x86_64

/private/tmp/mas-20210506-97137-1ektys4: warning: failed loading manifest for 'mas-20210506-97137-1ektys4' from cache: unknown system error while operating on /Users/zoltar/Library/Caches/org.swift.swiftpm/manifests/manifest.db.lock
/private/tmp/mas-20210506-97137-1ektys4: error: manifest parse error(s):
sandbox-exec: sandbox_apply: Operation not permitted
```

**Comment by chris-araman** [comment]
Does adding `--disable-sandbox` to `swift build` in `script/build` help?

**Comment by phatblat** [comment]
Yeah, that's what's causing the errors. I'll give it a try.

This gets rid of the manifest cache warning:

```
swift build --manifest-cache none
```

**Comment by phatblat** [comment]
Looks like both of these flag fix the issue

```
swift build --disable-sandbox --manifest-cache none ...
```
