### ISSUE TITLE
`outdated`: fetch-response is unable to open the file

### ISSUE THREAD

**Issue by Stanzilla** [mas-cli/mas#366]
## Your Environment

- `mas version`: 1.8.1
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 11.3.1

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/master)
  - Xcode version: 10.?

## Describe the Bug

> A clear and concise description of what the bug is.

Error in output: `2021-05-08 01:54:58.349 mas[29767:334725] INFO: fetch-response is unable to open the file /Users/stan/Library/Caches/com.mphys.mas-cli/fsCachedData/1A7AAD60-6485-4734-8066-9ED19E0A7780. Errno: 2`

## To Reproduce

1. `mas outdated`
1. See error

## Expected Behavior

> A clear and concise description of what you expected to happen.

No error

## Actual Behavior

> A clear and concise description of what actually happened.

error

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```bash
$ mas outdated
...
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

**Comment by chris-araman** [comment]
This is #337.

**Comment by phatblat** [comment]
This should be fixed in 1.8.2. We are working out some issues with updating Homebrew, but you can install the new version using the .pkg installer on the releases page.
