### ISSUE TITLE
`signin` fails on Mavericks

### ISSUE THREAD

**Issue by frasc** [mas-cli/mas#37]
On Mavericks it crashes with:
mas signin myemail@srvr.com "**********"
dyld: Library not loaded: /System/Library/PrivateFrameworks/StoreFoundation.framework/Versions/A/StoreFoundation
  Referenced from: /Users/frasc/./mas
  Reason: image not found
Trace/BPT trap: 5

Is it possible to get it to work on older OS versions ?

Thanks a lot, that's an awesome idea!

**Comment by argon** [comment]
I don't have the time or resources to reverse engineer older versions of the App Store frameworks so older versions won't be supported.

—A
