### ISSUE TITLE
🐛 [BUG] Update not working for certain apps

### ISSUE THREAD

**Issue by cadenkriese** [mas-cli/mas#371]
## Your Environment

- mas version: 1.8.2
- macOS version: 11.3.1 (ARM)

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [ ] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [ ] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [ ] Built from source
  - Fork/branch: ? (e.g. mas-cli/master)
  - Xcode version: 10.?

## Describe the Bug

> When running `mas update`, some apps try to update to versions I cannot even see when I open the app store myself. These updates fail and `mas outdated` still shows an update as being available. 

## To Reproduce

1. Run `mas update`.
2. Some apps will attempt to update but end up not changing

## Expected Behavior

> The app either update successfully or does not show the update as available if it is not truly available yet.

## Actual Behavior

> mas attempts to update apps to versions that may have not been released yet, this update fails and mas still says those apps are outdated.

## Screenshots, Terminal Output

![mas-error](https://user-images.githubusercontent.com/13630061/117555518-2965a700-b01d-11eb-8526-2241e6d334e2.gif)

<img width="259" alt="screenshot-2021-05-08-at-16 49 18" src="https://user-images.githubusercontent.com/13630061/117555544-5ca83600-b01d-11eb-89a1-c36e2bbc2727.png">

**Comment by chris-araman** [comment]
@cadenkriese, thanks for the report! This looks like another instance of #336, as both Endel and 1Blocker are available for iOS/iPadOS and macOS.
