### ISSUE TITLE
Place to discuss mas development / help with debugging error

### ISSUE THREAD

**Issue by rgoldberg** [mas-cli/mas#378]
Is there a place to discuss mas development?

I want to debug mas to investigate `mas outdated` not reporting certain apps as outdated when the MAS gui reports them as outdated.

I successfully built & tested `main` from the command line using `./script/build` & `./script/test`, respectively, but I get the following error when I try to debug mas in Xcode 12.5 (12E262) on macOS 11.3.1 (20E241) on an Intel Mac Mini 2014:

```
unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos'
```

How can I debug mas?

I can't remember if I ran into this problem when I debugged mas while working on `mas update` & `mas outdated`…

Once I investigate the issue, I'll open a separate issue to track it.

**Comment by chris-araman** [comment]
I'm not aware of any place other than GitHub to discuss mas development.

I haven't seen the error you mention. It looks like maybe you're trying to build mas for iOS? Command line executables are not supported on iOS.

If you have a fresh git clone of mas-cli/mas, in the main branch, you should be able to build (for macOS) with just:
```
script/bootstrap
script/build
```

**Comment by rgoldberg** [comment]
All was fixed by a fresh clone.  Not sure why my previous clone that was up-to-date with `main` had the problem but the new clone doesn't.
