### ISSUE TITLE
👷🏻 Set up M1 mini as GitHub self-hosted runner

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#380]
https://docs.github.com/en/actions/hosting-your-own-runners

**Comment by chris-araman** [comment]
⚠️ Self-hosted runners might be open to attack from forks of the public `mas` repository:
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
