### ISSUE TITLE
🐛 [BUG] v1.8.2 package file?

### ISSUE THREAD

**Issue by brian163** [mas-cli/mas#383]
Are mas.pkg files no longer being posted as of 1.8.2? All I see is source code and bottle files? (Sorry if I'm confused, I'm not a developer.)

Any guidance would be appreciated.

**Comment by chris-araman** [comment]
[Here you go.](https://github.com/mas-cli/mas/releases/download/v1.8.2/mas.pkg) I'm not sure why it wasn't included with the rest of the release assets, but it's there now.

**Comment by phatblat** [comment]
Sorry about that, @brian163. I deleted and recreated the release after we worked out some issues. Didn't notice that the .pkg file got dropped in the process. Thanks for pointing this out!

**Comment by brian163** [comment]
Thanks for the update!
