### ISSUE TITLE
Upgrade PromiseKit to 6.14.0

### ISSUE THREAD

**Issue by rgoldberg** [mas-cli/mas#388]
Upgrade PromiseKit to 6.14.0

**Comment by chris-araman** [comment]
This seems to fix some compiler warnings, but doesn't seem to offer new functionality or fixes for `mas`. Is there something specific you're hoping to use in this release, @rgoldberg?

**Comment by rgoldberg** [comment]
Was just interested in getting rid of the compiler warnings and generically upgrading to the latest.
