### ISSUE TITLE
OS X 10.9 Mavericks Support

### ISSUE THREAD

**Issue by silicontrip** [mas-cli/mas#4]
I'm getting the following error running mas.

```text
dyld: Library not loaded: /System/Library/PrivateFrameworks/StoreFoundation.framework/Versions/A/StoreFoundation
  Referenced from: /usr/local/bin/mas
  Reason: image not found
zsh: trace trap  mas list
```

Can mas be built without StoreFoundation?

Thanks

**Comment by argon** [comment]
Could you give more information about OS version and how you're running it?

—A

**Comment by silicontrip** [comment]
I'm running this on a 10.9 machine.
simply entering the command "mas list"

**Comment by argon** [comment]
I don't have access to a Mavericks machine at the moment so I am unable to confirm the problem or explore a workaround. Unfortunately it's possible that 10.9 simply can't be supported if the Framework layout has changed.

Would you be able to copy & paste the output of `ls /System/Library/PrivateFrameworks` from your machine so I can see what could be missing?

**Comment by silicontrip** [comment]
There is a StoreKit, but that looks like it's for in app payments.

I did try building mas-cli but had alsorts of compiler issues (from errors when installing the JSON gem) to not knowing how to process .swift files and finally getting errors compiling the Private StoreFoundation headers.

```
quadrant~/Developer/mas% ./script/build 
▸ Cleaning mas-cli/mas [Release]
▸ Check Dependencies
▸ Clean Succeeded
▸ Building mas-cli/mas [Release]
▸ Check Dependencies
▸ Processing mas-cli-Info.plist
▸ Compiling Account.swift

❌  /Users/mark/Developer/mas/mas-cli/PrivateHeaders/StoreFoundation/ISServiceProxy.h:19:52: expected ')'

typedef void (^ISErrorHandler)(NSError * __nonnull error);
        ^
```

I'm using Xcode 6.2
Here is the contents of /System/Library/Frameworks

AGL.framework
AVFoundation.framework
AVKit.framework
Accelerate.framework
Accounts.framework
AddressBook.framework
AppKit.framework
AppKitScripting.framework
AppleScriptKit.framework
AppleScriptObjC.framework
AppleShareClientCore.framework
ApplicationServices.framework
AudioToolbox.framework
AudioUnit.framework
AudioVideoBridging.framework
Automator.framework
CFNetwork.framework
CalendarStore.framework
Carbon.framework
Cocoa.framework
Collaboration.framework
CoreAudio.framework
CoreAudioKit.framework
CoreData.framework
CoreFoundation.framework
CoreGraphics.framework
CoreLocation.framework
CoreMIDI.framework
CoreMIDIServer.framework
CoreMedia.framework
CoreMediaIO.framework
CoreServices.framework
CoreText.framework
CoreVideo.framework
CoreWLAN.framework
CoreWiFi.framework
DVComponentGlue.framework
DVDPlayback.framework
DirectoryService.framework
DiscRecording.framework
DiscRecordingUI.framework
DiskArbitration.framework
DrawSprocket.framework
EventKit.framework
ExceptionHandling.framework
FWAUserLib.framework
ForceFeedback.framework
Foundation.framework
GLKit.framework
GLUT.framework
GSS.framework
GameController.framework
GameKit.framework
ICADevices.framework
IMCore.framework
IMServicePlugIn.framework
IOBluetooth.framework
IOBluetoothUI.framework
IOKit.framework
IOSurface.framework
ImageCaptureCore.framework
ImageIO.framework
InputMethodKit.framework
InstallerPlugins.framework
InstantMessage.framework
JavaFrameEmbedding.framework
JavaScriptCore.framework
JavaVM.framework
Kerberos.framework
Kernel.framework
LDAP.framework
LatentSemanticMapping.framework
MapKit.framework
MediaAccessibility.framework
MediaLibrary.framework
MediaToolbox.framework
Message.framework
NetFS.framework
OSAKit.framework
OpenAL.framework
OpenCL.framework
OpenDirectory.framework
OpenGL.framework
PCSC.framework
PreferencePanes.framework
PubSub.framework
Python.framework
QTKit.framework
Quartz.framework
QuartzCore.framework
QuickLook.framework
QuickTime.framework
Ruby.framework
RubyCocoa.framework
SceneKit.framework
ScreenSaver.framework
Scripting.framework
ScriptingBridge.framework
Security.framework
SecurityFoundation.framework
SecurityInterface.framework
ServiceManagement.framework
Social.framework
SpriteKit.framework
StoreKit.framework
SyncServices.framework
System.framework
SystemConfiguration.framework
TWAIN.framework
Tcl.framework
Tk.framework
VideoDecodeAcceleration.framework
VideoToolbox.framework
WebKit.framework
module.map
vecLib.framework

**Comment by argon** [comment]
Thanks for that info, could you post the contents of /System/Library/**Private**Frameworks please, not just /System/Library/Frameworks

**Comment by silicontrip** [comment]
Sorry misread your original request

AOSAccounts.framework
AOSKit.framework
AOSMigrate.framework
AOSNotification.framework
AOSUI.framework
AVConference.framework
AVCore.framework
AVFoundationCF.framework
AccessibilityBundles.framework
AccountsDaemon.framework
Admin.framework
AirPortDevices.framework
AirTrafficHost.framework
Altitude.framework
AppContainer.framework
AppSandbox.framework
Apple80211.framework
AppleAppSupport.framework
AppleFSCompression.framework
AppleGVA.framework
AppleGVACore.framework
AppleLDAP.framework
AppleProfileFamily.framework
ApplePushService.framework
AppleSRP.framework
AppleScript.framework
AppleSystemInfo.framework
AppleVA.framework
Assistant.framework
AssistantServices.framework
AssistiveControlSupport.framework
Backup.framework
BezelServices.framework
Bom.framework
BookKit.framework
BookmarkDAV.framework
BrowserKit.framework
ByteRangeLocking.framework
CalDAV.framework
Calculate.framework
CalendarAgent.framework
CalendarAgentLink.framework
CalendarDraw.framework
CalendarFoundation.framework
CalendarPersistence.framework
CalendarUI.framework
CaptiveNetwork.framework
CharacterPicker.framework
ChunkingLibrary.framework
ClockMenuExtraPreferences.framework
CloudServices.framework
CommerceKit.framework
CommonAuth.framework
CommonCandidateWindow.framework
CommunicationsFilter.framework
ConfigProfileHelper.framework
ConfigurationProfiles.framework
ContactsAssistantServices.framework
ContactsAutocomplete.framework
ContactsData.framework
ContactsFoundation.framework
ContactsUI.framework
CoreADI.framework
CoreAUC.framework
CoreAVCHD.framework
CoreChineseEngine.framework
CoreDAV.framework
CoreDaemon.framework
CoreFP.framework
CoreHandwriting.framework
CoreKE.framework
CoreLSKD.framework
CoreLSKDMSE.framework
CoreMediaAuthoring.framework
CoreMediaIOServicesPrivate.framework
CoreMediaPrivate.framework
CoreMediaStream.framework
CorePDF.framework
CoreProfile.framework
CoreRAID.framework
CoreRecents.framework
CoreRecognition.framework
CoreSDB.framework
CoreServicesInternal.framework
CoreSymbolication.framework
CoreThemeDefinition.framework
CoreUI.framework
CoreUtils.framework
CoreWLANKit.framework
CrashReporterSupport.framework
DCERPC.framework
DMNotification.framework
DVD.framework
DashboardClient.framework
DataDetectors.framework
DataDetectorsCore.framework
DebugSymbols.framework
DesktopServicesPriv.framework
DeviceLink.framework
DeviceToDeviceKit.framework
DeviceToDeviceManager.framework
DiagnosticLogCollection.framework
DigiHubPreference.framework
DirectoryEditor.framework
DirectoryServer.framework
DiskImages.framework
DiskManagement.framework
DisplayServices.framework
EAP8021X.framework
EFILogin.framework
EasyConfig.framework
EmailAddressing.framework
ExchangeWebServices.framework
FTClientServices.framework
FTServices.framework
FWAVC.framework
FWAVCPrivate.framework
FaceCore.framework
FaceCoreLight.framework
FamilyControls.framework
FileSync.framework
FindMyMac.framework
FinderKit.framework
GPUSupport.framework
GameKitServices.framework
GenerationalStorage.framework
GeoKit.framework
GeoServices.framework
GraphKit.framework
GraphicsAppSupport.framework
HDAInterface.framework
HeimODAdmin.framework
Heimdal.framework
HelpData.framework
IASUtilities.framework
ICANotifications.framework
IDS.framework
IDSCore.framework
IDSFoundation.framework
IDSSystemPreferencesSignIn.framework
IMAP.framework
IMAVCore.framework
IMCore.framework
IMDMessageServices.framework
IMDPersistence.framework
IMDaemonCore.framework
IMFoundation.framework
IMTranscoding.framework
IMTransferServices.framework
IOAccelMemoryInfo.framework
IOAccelerator.framework
IOPlatformPluginFamily.framework
ISSupport.framework
IconServices.framework
IncomingCallFilter.framework
Install.framework
International.framework
InternetAccounts.framework
IntlPreferences.framework
JavaApplicationLauncher.framework
JavaLaunching.framework
KerberosHelper
KerberosHelper.framework
Librarian.framework
LibraryRepair.framework
LoginUIKit.framework
Lookup.framework
MDSChannel.framework
MMCS.framework
MMCSServices.framework
MachineSettings.framework
Mail.framework
MailCore.framework
MailService.framework
MailUI.framework
ManagedClient.framework
Mangrove.framework
Marco.framework
MediaControlSender.framework
MediaKit.framework
MediaUI.framework
MessageProtection.framework
MessagesHelperKit.framework
MessagesKit.framework
MobileDevice.framework
MonitorPanel.framework
MultitouchSupport.framework
NetAuth.framework
NetFSServer.framework
NetworkDiagnosticsUI.framework
NetworkMenusCommon.framework
NetworkStatistics.framework
Notes.framework
Noticeboard.framework
OAuth.framework
OfficeImport.framework
OpenDirectoryConfig.framework
OpenDirectoryConfigUI.framework
PSNormalizer.framework
PackageKit.framework
PacketFilter.framework
PassKit.framework
PasswordServer.framework
PerformanceAnalysis.framework
PhoneNumbers.framework
PhysicsKit.framework
PlatformHardwareManagement.framework
PodcastProducerCore.framework
PodcastProducerKit.framework
PreferencePanesSupport.framework
PrintingPrivate.framework
ProKit.framework
ProofReader.framework
ProtocolBuffer.framework
RTCReporting.framework
RemotePacketCapture.framework
RemoteViewServices.framework
Restore.framework
SAObjects.framework
SCEP.framework
SMBClient.framework
SPSupport.framework
Safari.framework
SafariServices.framework
ScreenReader.framework
ScreenSharing.framework
SecCodeWrapper.framework
SecureNetworking.framework
SecurityTokend.framework
SemanticDocumentManagement.framework
ServerFoundation.framework
ServerInformation.framework
SetupAssistantSupport.framework
ShareKit.framework
Sharing.framework
Shortcut.framework
SleepServices.framework
Slideshows.framework
SocialAppsCore.framework
SocialUI.framework
SoftwareUpdate.framework
SpeechDictionary.framework
SpeechObjects.framework
SpeechRecognitionCore.framework
SpotlightIndex.framework
StoreJavaScript.framework
StoreUI.framework
StoreXPCServices.framework
StreamingZip.framework
Suggestions.framework
Symbolication.framework
Symptoms.framework
SyncServicesUI.framework
SyncedDefaults.framework
SystemAdministration.framework
SystemMigration.framework
SystemUIPlugin.framework
TCC.framework
TrustEvaluationAgent.framework
UIRecording.framework
Ubiquity.framework
Uninstall.framework
UniversalAccess.framework
VCXMPP.framework
VectorKit.framework
VideoConference.framework
VideoProcessing.framework
ViewBridge.framework
WeatherKit.framework
WebContentAnalysis.framework
WebFilterDNS.framework
WebInspector.framework
WebInspectorUI.framework
WebKit2.framework
WhitePages.framework
WiFiCloudSyncEngine.framework
WirelessDiagnosticsSupport.framework
XMPPCore.framework
XPCObjects.framework
XPCService.framework
XQuery.framework
iCalendar.framework
iLifeMediaBrowser.framework
iLifeSlideshow.framework
iPod.framework
iPodSync.framework
iTunesAccess.framework
kperf.framework
login.framework
nt.framework
oncrpc.framework
vmutils.framework

**Comment by argon** [comment]
I don't think it's going to be feasible to support Mavericks, it looks like Apple changed the Framework layout. I don't have the availability to work on backward compatibility. Sorry.
