### ISSUE TITLE
No longer available in Homebrew

### ISSUE THREAD

**Issue by voltuer** [mas-cli/mas#402]
I tried installing it on my Mac with M1 chip and I get this:

```
% brew install mas

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by chris-araman** [comment]
It's still there:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/mas.rbterm

```
> brew info mas
mas: stable 1.8.2 (bottled), HEAD
Mac App Store command-line interface
https://github.com/mas-cli/mas
/opt/homebrew/Cellar/mas/1.8.2 (7 files, 745.8KB) *
  Poured from bottle on 2021-05-08 at 17:43:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mas.rb
License: MIT
==> Requirements
Build: Xcode >= 12.2 ✔
Required: macOS ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
fish completions have been installed to:
  /opt/homebrew/share/fish/vendor_completions.d
==> Analytics
install: 6,485 (30 days), 29,192 (90 days), 105,952 (365 days)
install-on-request: 6,464 (30 days), 29,113 (90 days), 104,943 (365 days)
build-error: 0 (30 days)
```

Are you running macOS Catalina 10.15 or later? If not, you can install from our custom tap:
https://github.com/mas-cli/mas#%EF%B8%8F-older-macos-versions

If you are, what does `brew doctor` show?

**Comment by tr4g** [comment]
I'm running Big Sur 11.4 on a Mac Mini with M1 chip. May that be the problem?

**Comment by chris-araman** [comment]
I'm sorry. You did say M1 in your original report, which implies Big Sur. Big Sur and M1 are both supported. That is not the problem. 

1. What does `brew doctor` show?
1. What does `brew update` show?

**Comment by chris-araman** [comment]
Similar to https://github.com/cli/cli/issues/3949.

**Comment by chris-araman** [comment]
@tr4g, it sounds like the issue you're experiencing is an issue with your Homebrew installation, not with mas-cli. Please try [troubleshooting](https://docs.brew.sh/Troubleshooting) Homebrew.
