### ISSUE TITLE
Problem with special characters in passwords

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#41]
Hi,

if i try to connect to the MAS with a password containing a special character i have to mask it, to get in. 

For example:

`mas signin MyUsername My!Password` does not work, but ...

`mas signin MyUsername My\!Password` will sign me in.

Thanx in advance.

Kind regards
Efty

**Comment by argon** [comment]
This is down to your shell rather than mas. It probably works if you wrap the password in quotes but it's normal for shells.

**Comment by EftyEdge** [comment]
Hi Andrew,

thank you very much for your quick reply and the tip. Really - i’m so sorry, but really i didn’t knew that this is normal in shells.

Thanx again and kind regards
Thomas (Efty)

P.S. I worte a litte shell script to automate the search and install the Apps by name during a fresh setup of my MBP. Maybe it’s useful for you or someone else!?



echo "Apple ID and Password for the Mac App Store... "
read username password

# Check if the 'Mac App Store' CLI is installed
[ ! -f "`which mas`" ] && brew install mas

# login to the 'Mac App Store'
mas signin $username $password

# Convert the App-Name to the Product Identifier
function install () {

  # Check if the App is already installed
  mas list | grep -i "$1" > /dev/null

  if [ "$?" == 0 ]; then
    echo "==> $1 is already installed..."
  else
    echo "==> $1 is not installed..."
    mas search "$1" | { read app_ident app_name ; mas install $app_ident ; }
  fi
}

# Search for the Apps in 'Mac App Store‘ and install it
install "Apple Configurator 2"
install "Banking 4x"
install "Better Battery"
install "Deliveries"
install "Display Menu"
install "Irvue"
install "Keynote"
install "Micro Snitch"
install "Moom"
install "Numbers"
install "Pages"
install "Palua"
install "PopClip"
install "PTT"
install "Reeder"
install "The Unarchiver"
install "Wifi Explorer"
install "Wimoweh"
install "Xcode"

# 'Mac App Store' signout
mas signout




> Am 08.09.2016 um 12:08 schrieb Andrew Naylor <notifications@github.com>:
> 
> This is down to your shell rather than mas. It probably works if you wrap the password in quotes but it's normal for shells.
>

**Comment by nicolinuxfr** [comment]
@EftyEdge thanks for your script, it's much easier to auto install apps this way ! 👍 

It's not the subject, but I wish mas could install with the name and not only the ID…

**Comment by argon** [comment]
@nicolinuxfr `mas` does provide the `search` command but it is not straightforward to provide `install <name>` due to the way the App Store handles names
