### ISSUE TITLE
Some apps report incorrect versions

### ISSUE THREAD

**Issue by andrewcrook** [mas-cli/mas#413]
## Your Environment

- `mas version`: ` 1.8.3`
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.1...
```
      System Version: macOS 11.5.2 (20G95)
      Kernel Version: Darwin 20.6.0
```

### mas Install Method

- [`X`] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?   `12.5.1 (12E507)`

## Describe the Bug

> A clear and concise description of what the bug is.

```
some of the applications listed by mas as outdated
Remain outdated after updating. 
because the versions detected as outdated were not the latest 
```

## To Reproduce

```
mas outdated 
mas upgrade
mas outdated 
```

## Expected Behavior

> A clear and concise description of what you expected to happen.

`no outdated apps should remain`

## Actual Behavior

`several apps report as outdated`

> A clear and concise description of what actually happened.

```
mas  outdated

1376402589 StopTheMadness (23.0 -> 23.1)
1365531024 1Blocker (3.16.2 -> 4.1.1)
1440006971 Tabs Saver for Safari (2.9.0 -> 2.9.5)
1549370672 Save to Raindrop.io (5.4.3 -> 5.4.5)
922765270 LiquidText (1.1.9 -> 5.0.6)
1498912833 Highlights (2021.1.1 -> 2021.1.4)
1219074514 Vectornator (4.2.2 -> 4.2.5)
1444383602 GoodNotes (5.7.22 -> 5.7.29)
```
```
mas upgrade  

Upgrading 4 outdated applications:
1Blocker (3.16.2), LiquidText (2.0.6), GoodNotes (5.7.26), Highlights (2021.1.1)
==> Downloading 1Blocker: Ad Blocker & Privacy
==> Installed 1Blocker: Ad Blocker & Privacy
==> Downloading LiquidText
==> Installed LiquidText
==> Downloading GoodNotes 5
==> Installed GoodNotes 5
==> Downloading Highlights: PDF Research Notes
==> Installed Highlights: PDF Research Notes
```

```
mas  outdated

1365531024 1Blocker (3.16.2 -> 4.1.1)
1498912833 Highlights (2021.1.1 -> 2021.1.4)
922765270 LiquidText (2.0.6 -> 5.0.6)
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

`No, however, I thought it was improving
`

**Comment by chris-araman** [comment]
Thanks for reporting this @andrewcrook. However, the issue is already tracked in pinned issue #384. Pull requests are welcome!
