### ISSUE TITLE
App always upgrades even if no new version available

### ISSUE THREAD

**Issue by fpesch** [mas-cli/mas#416]
## Your Environment

- `mas version`: 1.8.3
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): `System Version: macOS 11.6 (20G165) Kernel Version: Darwin 20.6.0`

### mas Install Method

- [X] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

Mas always upgrades a specific app. Even if there is no upgrade available for it.

## To Reproduce

1. `mas install 1018301773` or `mas "AdBlock Pro", id: 1018301773` via `Brewfile`
2. brew upgrade

## Expected Behavior

App only gets upgraded if there is an upgrade available for it.

## Actual Behavior

See bug description.

**Comment by chris-araman** [comment]
@bpesch, thanks for the report, but this is already tracked by #384. Pull requests are welcome!
