### ISSUE TITLE
Compatible Updates 

### ISSUE THREAD

**Issue by drewauff** [mas-cli/mas#421]
MAS needs the ability to filter updates. ie. Im on Catalina and when some devs. Apple included, decide to update there apps to Big Sur+ only, MAS asks If id like to download/install an older compatible version. These incompatible apps (I have 5) need to be filtered out otherwise "upgrading all" is rendered useless because installer wont progress. Even if you select yes to download older version it remains on list.

**Comment by hakamadare** [comment]
good news!  this is already fixed in #422, which is merged but not yet released.

**Comment by mathbunnyru** [comment]
Thanks @hakamadare, that's great news!
@chris-araman @phatblat I think this issue can be closed and it would be super-great to have a new release :heart:

**Comment by phatblat** [comment]
Closing this as #422 already addresses this request. We're about to release 1.8.4 with this included.
