### ISSUE TITLE
Add flag to suppress warnings

### ISSUE THREAD

**Issue by drewauff** [mas-cli/mas#431]
Can you add a flag to suppress "Warning Identifier Not Found"

I have at least 20 of them and I use mas piped through `cut -d 'W' -f1` to remove them but this does not work anymore.

In fact it seems  using cut,  grep, awk, sed etc. does not work as expected since th last update.

**Comment by drewauff** [comment]
I am running this through a small zsh/fzf widget, this :
`mas outdated 2>/dev/null | awk '{$1=""; print $0}' | fzf | awk '{print $1}' | xargs -I % mas upgrade %`

It runs just fine says its updating then spits out this error and a dialog box.

But I get this error :
`Error: Download request failed: The network connection was lost.`

And if I run a simple :
`mas outdated 2>/dev/null | fzf | xargs -I % mas upgrade %` 

I get this error : 
`Warning: Nothing found to upgrade`

**Comment by chris-araman** [comment]
> Error: Download request failed: The network connection was lost.

This error has nothing to do with `fzf` or `mas` sending errors and warnings to `stderr`.

Can you help me understand what you're trying to accomplish? It looks like you're using this sequence of commands to upgrade all outdated App Store apps. For that, you can simply run `mas upgrade`. If you want to ignore the `Nothing found to upgrade` warning, run `mas upgrade 2&>/dev/null`. (I missed the ampersand in my previous comment.)

I hope that helps.

**Comment by chris-araman** [comment]
Ah, okay. I've read the `fzf` [usage](https://github.com/junegunn/fzf#usage) now.

I think you want:
```
mas outdated 2&>/dev/null | fzf | xargs -I % mas upgrade %
```

**Comment by chris-araman** [comment]
@drewauff, which version of `mas` are you running?
```
mas version
```

As of 1.8.4, errors and warnings are emitted to `stderr`, meaning `mas outdated 2>/dev/null | fzf` should not pipe warnings to `fzf`. However, running `mas upgrade` with no arguments when no apps are outdated will yield such a warning.

How is your widget meant to handle this case?

**Comment by drewauff** [comment]
Im running 1.8.5


Basically, you run the alias,  a list of applications that have updates pending are listed, the you select 1 or as many as you like hit enter and then it updates.

Further clarificaton, `awk '{$1--"; print $9}'` outputs everything except the first column, `awk '{print $1}'` is just parsing the whatever entry is in the first column to be executed via mas upgrade.

I hope this is of some help.

**Comment by chris-araman** [comment]
Got it. How does your script handle the case when there's nothing to update? What is expected to happen?

**Comment by chris-araman** [comment]
Alternatively, if you just want the warning to be emitted to `stdout` along with the list of outdated apps, as before:
`mas outdated 2>&1`

**Comment by drewauff** [comment]
When there is nothing to update it returns to command line.

**Comment by drewauff** [comment]
> Alternatively, if you just want the warning to be emitted to `stdout` along with the list of outdated apps, as before:
> 
> ```
> mas outdated 2>&1
> ```

nope, spews a messsage "identifier `insert identifier` unknown.

**Comment by drewauff** [comment]
ok..new error time..Using this `mas outdated 0>&1 2>/dev/null | fzf | awk '{print $1}' | xargs -I % mas upgrade % ` 
It gives the standard updated outdated package, then a dialog box pops up the `network connection lost` so I close that and in iterm ctrl-z to kill process and now I get
` Error: Download request failed: The network connection was lost.`

**Comment by drewauff** [comment]
hmmm, just ran `mas upgrade "app name` and blood hell got the download request error again. So maybe its mas itself?

**Comment by drewauff** [comment]
Ok, I tried to "sign-in" but apparently Catalina is not supported. Bugger!

**Comment by chris-araman** [comment]
@drewauff, you will need to sign in using the App Store app.
https://github.com/mas-cli/mas#%EF%B8%8F-known-issues

**Comment by drewauff** [comment]
beat you to it,  already had coursery  read through that. purchase is not supported on Catalina but did not see anytning about signin

**Comment by drewauff** [comment]
sorry accidental close....

**Comment by drewauff** [comment]
so, been experimenting with mas, no luck whatsoever....

**Comment by chris-araman** [comment]
@drewauff, I'm not sure why you're seeing the errors you're seeing, but they have to do with your network connectivity and your App Store sign-in state. I don't seen evidence of `mas` bugs here, just a change to how warnings are emitted to the console, which I've addressed above. This command works for both the "some apps are outdated" and "no apps are outdated" cases:
```
mas outdated 0>&1 2>/dev/null | fzf | awk '{print $1}' | xargs -I % mas upgrade %
```

**Comment by drewauff** [comment]
@chris-araman I added `awk '{$1=""; print $0}'` to hide the APP ID numbers, and THATS most likely creating the error.

**Comment by drewauff** [comment]
hmm, seems a reboot did  the trick..

Thanks for putting up with me haha, appreciate your time and patience.

-
Andy

note: Would it be possible to get an option to hide the APP ID numbers?
