### ISSUE TITLE
🐛 [BUG] 🙏[HELP WANTED] Mas command no response question

### ISSUE THREAD

**Issue by circumeo** [mas-cli/mas#436]
## Your Environment

- `mas version`: 1.8.5
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 11.6.1

![스크린샷 2021-11-24 오후 5 08 55](https://user-images.githubusercontent.com/76243664/143199626-84a30efd-e939-4be1-95d8-48eae08a1f07.png)

As shown in the picture, the link between mas and the app store has been unlocked. Help me! 🙏
Thank you in advance

**Comment by phatblat** [comment]
@circumeo I'm not clear on what you mean by saying the "link between mas and the app store has been unlocked". Can you be more specific?

The issue that I see from your `uninstall` attempt in the above screenshot is that you did not run the command as root. Try `sudo mas uninstall <appID>`

**Comment by phatblat** [comment]
Closing since there has been no reply in some time to help clarify this issue.
