### ISSUE TITLE
`outdated` always lists current NordVPN

### ISSUE THREAD

**Issue by nohli** [mas-cli/mas#439]
## Your Environment

- `mas version`: 1.8.5
- macOS version: 12.0.1 (M1)

### mas Install Method

- [x] `brew install mas` (homebrew-core)

## Describe the Bug

mas upgrades the 'outdated' NordVPN every time 'mas upgrade' is called.

## To Reproduce

1. Install NordVPN via App Store
1. 'mas upgrade'

## Expected Behavior

It doesn't upgrade NordVPN every time.

## Actual Behavior

It upgrades NordVPN every time.

## Screenshots, Terminal Output

```bash
achim@Achims-MacBook ~ % mas upgrade
Upgrading 1 outdated application:
NordVPN (7.0.0)
==> Installed NordVPN: VPN Fast & Secure
achim@Achims-MacBook ~ % mas upgrade
Upgrading 1 outdated application:
NordVPN (7.0.0)
==> Downloading NordVPN: VPN Fast & Secure
==> Installed NordVPN: VPN Fast & Secure
achim@Achims-MacBook ~ % mas upgrade
Upgrading 1 outdated application:
NordVPN (7.0.0)
==> Installed NordVPN: VPN Fast & Secure
```

## Additional Context

Before, I used NordVPN IKE and it didn't happen.
It only happens with NordVPN.

**Comment by chris-araman** [comment]
@nohli, please see Known Issues:
https://github.com/mas-cli/mas#%EF%B8%8F-known-issues

**Comment by nohli** [comment]
Thanks 🙏🏽
