### ISSUE TITLE
🐛 [BUG] "Outbank" can not be found but installed via id

### ISSUE THREAD

**Issue by kennymc-c** [mas-cli/mas#442]
## Your Environment

- `mas version`: 1.8.5
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 12.0.1

### mas Install Method

- [X] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

When I search for a specific app (Outbank) with `mas search outbank`, I get `Error: No results found`, even though I can find this app with the same search in the App Store app.
Also a search for the ID (1094255754) brings no results. But I can install the app with `mas install 1094255754`.
What could be the reason for this? I know there was a recent change to the bundle identifier on this app. Or maybe mas is using a different regional app store where this app is not available?
Maybe this is not the only app with this problem.

## To Reproduce

`mas search outbank` or `mas search 1094255754`

## Expected Behavior

You should see the same search results as with the App Store app

## Actual Behavior

You see different search results

**Comment by chris-araman** [comment]
@kennymc-c, it's possible this app was removed for sale from the App Store, or was removed for sale in your region. If you had already purchased the app, though, you'd still be able to download it again. I suspect that may be what happened here, but am not sure how to verify it.

**Comment by kennymc-c** [comment]
No, it was not removed. I searched for older closed issues and found #221. Outbank was also listed there. So it is defintly not the only app with this problem. Some of them are fixed but not Outbank.

**Comment by chris-araman** [comment]
What region is your account in, @kennymc-c? I don't see "Outbank" when searching the U.S. Mac App Store region. I also checked iOS and iPadOS apps.

**Comment by kennymc-c** [comment]
My account region is Germany.

**Comment by chris-araman** [comment]
Got it. Thanks for your report, @kennymc-c! It looks like `mas` was not passing a `country` query parameter to the iTunes Search API. This will be resolved with #443.
