### ISSUE TITLE
Can it track iPhone/iPad (iOS/iPadOS) apps?

### ISSUE THREAD

**Issue by singularitti** [mas-cli/mas#446]
**Is your feature request related to a problem? Please describe.**
Can we have it to track iPhone/iPad (iOS/iPadOS) apps? When I do `mas list` or `brew bundle dump`, it does not seem to include those apps.

**Describe the solution you'd like**
To output iPhone/iPad (iOS/iPadOS) apps in `mas list` or `brew bundle dump`.

**Comment by chris-araman** [comment]
Hi, @singularitti. This issue is already tracked in #321.
