### ISSUE TITLE
🐛 [BUG] No package file for v1.8.6

### ISSUE THREAD

**Issue by brian163** [mas-cli/mas#450]
Can someone check the assets for v1.8.6? There is no package installer.

Thanks

**Comment by phatblat** [comment]
@brian163 Thanks for reporting. I've built the `.pkg` file and attached it to the 1.8.6 release. Here's a direct link for you convenience: https://github.com/mas-cli/mas/releases/download/v1.8.6/mas.pkg

**Comment by brian163** [comment]
thanks
