### ISSUE TITLE
bash completion script

### ISSUE THREAD

**Issue by matteocorti** [mas-cli/mas#453]
It would be nice to include in the packaging a bash-completion script.

I wrote a first working version (just the commands and the IDs of installed applications for the ```uninstall``` command).

If you want to integrate feel free: https://github.com/matteocorti/mas.completion

**Comment by steakknife** [comment]
The tool itself should output completions for various shells, i.e., `mas completions {ba,fi,z}sh`

**Comment by StefanLobbenmeier** [comment]
yeah ideally they are generated by the cli framework, but it seems the PR for adding this to the cli framework was rejected: https://github.com/Carthage/Commandant/pull/120

**Comment by rgoldberg** [comment]
Closing in favor of #678
