### ISSUE TITLE
`search` only accepts a single argument

### ISSUE THREAD

**Issue by brettrowberry** [mas-cli/mas#459]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 12.2.1

### mas Install Method

- [x] `brew install mas` (homebrew-core)

## Describe the Bug

Can't search for apps with multi-word titles.

## To Reproduce

1. `mas search Member Tools`
1. See error `Unrecognized arguments: "Tools"` 

Use single quotes
1. `mas search 'Member Tools'`
2. See `1549235640  AARP Perks (1.11)1549235640  AARP Perks (1.11)`

## Expected Behavior

Finds Member Tools app, https://apps.apple.com/us/app/member-tools/id391093033

## Actual Behavior

Doesn't parse multi-word titles without quotes. Doesn't find app with quotes.

**Comment by brettrowberry** [comment]
Both of these are iOS apps, so that may be a factor. Just discovered #321.

**Comment by phatblat** [comment]
All shells use the space character to separate arguments. You need to either quote multiple words (as your example shows), or escape the spaces with a backslash `\`

**Comment by phatblat** [comment]
It may be possible for mas to insert spaces between the arguments you supply before searching, however that feature would be in conflict with others such as #168 and #225

**Comment by brandon-fryslie** [comment]
I think this can be closed.  I have verified searching for multi-word titles does work.  
```
% mas search 'Blackmagic Disk Speed Test'
   425264550  Blackmagic Disk Speed Test (3.4.2)
   999260138  GPU Benchmark: System Test (1.2.5)
```

MacOS: Ventura 13.4
Mas version: 1.8.6

**Comment by brettrowberry** [comment]
You were right to close this. Just tested:

```
% mas search 'Member Tools'
   556360639  Hitask: Team Task Management   (19.4.0)
  1234485803  MCH My Club Hub                (1.1.9)
  6741502932  LDS Scripture Memorization     (1.01)
  1458235852  Fun LDS Games for Sundays      (2.28)
   598329798  Gospel Library                 (7.3.1)
  1360532665  Office Moving Alliance         (1.9)
  6456040475  Recur - Simplified AMS Tools   (4.1.0)
  1558924604  Disney Cast Life               (3.0.1)
  1630788532  Temple Appointment Scheduling  (1.04)
  6444296601  Strommar Member                (13)
  1473274914  Front Desk Attendant           (11.5)
  6742451551  LDS Church Hymns Recognizer    (1.0)
  1558126585  Local768                       (1.9)
  1631539791  Core Transit Mobile Tickets    (7.8.26)
   391093033  Member Tools                   (5.3.0)
  1006664302  JustServe                      (3.1.4)
  6503178615  VaultCord                      (1.0.1)
  1587475558  Hone Golf                      (4.4.2)
  1549235640  AARP Perks                     (1.17)
   642922942  My Spiritual Toolkit AA Steps  (6.1.3)
  6737236307  TxFlow.AI                      (3.98.1)
   885982973  FamilySearch Tree              (5.1.14)
   877780544  Celestron SkyPortal            (3.5.0)
  6740051768  Monivault                      (1.5.1)
   463553380  Sacred Music                   (2.5.4)
  1282236448  ホェールテニスデフゲーム                   (5.0)
  1438289999  Gift Card Balance (GCB)        (3.0.219)
  6742097207  NADA – Official Mobile App     (1.3)
  6504179485  TechHelp                       (1.4)
  6737542666  TNG Member                     (1.0.0)
  6449491173  Καταγραφικό INFOXOROS          (4.0)
  1245330433  Gospel Living                  (2.7.4)
  6478200239  Skyos Inventory                (2.2.1)
  6741032574  LDS Scriptures Search Tool     (1.0)
  6740244540  UFP - Staff Hub & Kiosk        (1.1.0)
  1626071574  Practice Attendance Tracker    (1.0.20)
  1579005361  Magic Starㅤ                    (1.1)
  1515773684  FemurOsteotomyTHR              (1.5)
   579194827  LDS Primary Stories            (2.5)
  1481214099  NaviToolHip                    (6.0)
```

macOS: Sequoia 15.5
mas: 2.2.2

Thanks!

**Comment by rgoldberg** [comment]
@brettrowberry 2.3.0, the next version that will be released (but that hasn't yet been released) will concentrate all positional arguments to `mas search` into a single search term (with a space inserted between arguments), so quotes / escapes will no longer be necessary.

I've been waiting for a few more user-facing improvements to release 2.3.0, but might just release it without more improvements since it's been a while since 2.2.2…
