### ISSUE TITLE
Maintainer Needed

### ISSUE THREAD

**Issue by argon** [mas-cli/mas#47]
Due to new work commitments I am no longer permitted to publish code to, or participate in, the mas project. Therefore I am seeking a maintainer to take good care of it and ensure it remains a useful project.

Please DM me via Twitter ([@argon](https://twitter.com/argon)) or send an email to the address on my GH profile if you wish to take it over. If you do take it over, please follow these rules:
- Do not claim to be the original author, so the license should retain my name, but feel free to add yourself to it once you have made any substantial contributions. Please keep my name and Twitter handle intact in the README - but you can move it around as you see fit.
- If at any point in the future, you want to stop maintaining the project:
  - If you find someone else to takeover the project, please ensure they will continue following these rules. 
  - If you cannot find anyone to take it over, please add an unmainted badge (see [here](http://unmaintained.tech)) to the README and transfer the project back to my GitHub account ([@argon](https://github.com/argon)). That will allow me to find a new maintainer myself or to at least keep the project available for historical purposes.
- My GitHub account ([@argon](https://github.com/argon)) should continue to be one of the owners of the project, but you will have full control over its future direction.

**Comment by brandondrew** [comment]
Wouldn't it be better to create a new organization for this project, to avoid any future shuffling around from one maintainer's account to another?

**Comment by rodionovd** [comment]
@brandondrew well it's actually inside its own organization right now :)

**Comment by phatblat** [comment]
@rodionovd can this issue be closed now?

**Comment by phatblat** [comment]
Thanks for all your hard work @argon, @rodionovd and others! I'm going to close this issue and add details about becoming a contributor in #117.
