### ISSUE TITLE
🐛 [BUG] Hangs without doing anything on macOS 13 Ventura

### ISSUE THREAD

**Issue by pixelcmtd** [mas-cli/mas#471]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 13.0 (22A5295i)

### mas Install Method

`brew install mas` (homebrew-core)

## Describe the Bug

Upgrading takes about half a minute to print

```
Upgrading n outdated applications:
App 1 (x.y.z), ...
```

and then does nothing else. (I've waited a few minutes on multiple occasions)

## To Reproduce

1. Run `mas upgrade`
2. Wait for a while

## Additional Context

I was kind of shocked when I noticed that nobody has reported this so far, as the Betas have been out for quite a while.
I'm not a heavy user of `mas` and it's mainly the thing that is blocking my `topgrade` at the end right now.

## Important Update

The issue [seems](https://github.com/mas-cli/mas/issues/471#issuecomment-1242991250) to be fixed on the latest Betas. If everything keeps working through the public release, we can close this.

**Comment by josh** [comment]
Seeing the same hang as well.

Installing appears to hang waiting for [`CKPurchaseController.performPurchase`](https://github.com/mas-cli/mas/blob/1892286a16d4367d2158d69734d2720219a8fa7b/Sources/PrivateFrameworks/CommerceKit/CKPurchaseController.h#L44) to call it's `completionHandler` when called from [`SSPurchase.perform`](https://github.com/mas-cli/mas/blob/1892286a16d4367d2158d69734d2720219a8fa7b/Sources/MasKit/AppStore/SSPurchase.swift#L62). Maybe something internally is silently failing or this private objective-c method no longer exists. That's about as far as I could debug the problem.

**Comment by BorzdeG** [comment]
In version 13.0 Beta (22A5342f), the "freeze" error no longer occurs, but the software update does not occur either

![image](https://user-images.githubusercontent.com/2332528/189477073-45299411-eff9-4c1e-87b5-3eecf53711d3.png)

**Comment by davipt** [comment]
Is this trying to install the apple developer tools? The tools are not available yet when running Xcode-select but they can be manually downloaded from the apple site. Even today, with iOS 16 RC already out, the tools still fail to install - "not available" or some error like that.

**Comment by pixelcmtd** [comment]
> In version 13.0 Beta (22A5342f), the "freeze" error no longer occurs, but the software update does not occur either

Same for me, as useful as it was on 12. (it had that sort of bug all the time)

![screenshot showing exactly the same behavior they experienced](https://user-images.githubusercontent.com/35269695/189536403-84dc4ee9-8105-4b69-b0e8-05eaf5134647.png)


I'd still like to keep the bug open at least until 13.0 is released, if everything still works fine then, we can close this as "Apple broke something, but they fixed it again, so whatever".

> Is this trying to install the apple developer tools?

It isn't. Why would you think that?

> The tools are not available yet when running Xcode-select but they can be manually downloaded from the apple site. Even today, with iOS 16 RC already out, the tools still fail to install - "not available" or some error like that.

That's weird. What exactly are you trying to do? I just downloaded and installed the XCode Betas and everything has been working fine as always.

**Comment by davipt** [comment]
> That's weird. What exactly are you trying to do? I just downloaded and installed the XCode Betas and everything has been working fine as always.

My bad. Got confused with the “Downloading Apple Developer”. I was talking about `xcode-select —install` that has been failing for many beta versions, but the previous version of the command-tools can be installed manually. Not related, I understand.

**Comment by phatblat** [comment]
Sounds like Ventura is going to land [next month](https://9to5mac.com/2022/09/09/macos-13-ventura-beta-7-available/). I'm going to install it on one of my Macs so I can keep an eye on this issue.

**Comment by pixelcmtd** [comment]
It works as well as it ever did on 22A380, which should be the release.
