### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by skull-squadron** [mas-cli/mas#473]
`mas uninstall` doesn't work (#313) and there doesn't seem to be any commits for the past 2 months.

**Comment by phatblat** [comment]
I'm still around @steakknife but we lost the only other maintainer to Apple. Sorry, but I've been pretty busy with a new job that has been taking all of my energy and brainpower so there hasn't been much left for open source work.

Very open to new contributors that want to help out!

**Comment by steakknife** [comment]
Argh! I'll see what I can from work for support. No promises.
