### ISSUE TITLE
🐛 [BUG] Xcode stuck at ver 13.4.1

### ISSUE THREAD

**Issue by luckman212** [mas-cli/mas#474]
## Your Environment

- `mas version`: 1.8.6
- macOS version: 12.6 (21G115)
- M1 Mac Mini

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [x] Xcode version: 14

## Describe the Bug

Xcode was updated to 14.0 but `mas info 497799835` still reports latest version as 13.4.1

## To Reproduce

1. type `mas info 497799835` :
```
Xcode 13.4.1 [0.0]
By: Apple Inc.
Released: 2022-06-02
Minimum OS: 12.0
Size: 12.64 GB
From: https://apps.apple.com/us/app/xcode/id497799835?mt=12&uo=4
```

## Expected Behavior

List version 14.0 

## Actual Behavior

see above

## Screenshots, Terminal Output

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1992842/189900849-fac60858-fb1a-44ef-9c52-f52ae73be8c7.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/1992842/189900937-c3421c78-aa8d-4adf-91aa-758dc14c89e6.png">

**Comment by StefanLobbenmeier** [comment]
Can you try again today? I also had this issue yesterday, but today it offerered this update. So there seems to be some kind of delay. 

But even yesterday in the search i was able to see the latest xcode version:
```
❯ mas search xcode
   497799835  Xcode                                              (14.0)
```

**Comment by luckman212** [comment]
Yes, it's working today! Strange. I guess the feed that mas hooks into has delayed data.
