### ISSUE TITLE
🐛 Error with M1 Mac

### ISSUE THREAD

**Issue by redreceipt** [mas-cli/mas#481]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 13.0

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [ ] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [ ] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [ ] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 14.1

## Describe the Bug

> A clear and concise description of what the bug is.

Simply trying to use it on my M1 Mac throws an error:

```sh
% mas lucky devcleaner
MasKit/MasKit.swift:23: Fatal error: PromiseKit event: pendingPromiseDeallocated
```

## To Reproduce

`mas lucky devcleaner`

## Expected Behavior

> A clear and concise description of what you expected to happen.

It installs

## Actual Behavior

> A clear and concise description of what actually happened.

It fails

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

See above
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

**Comment by rgoldberg** [comment]
@redreceipt Does this still occur? If so, can you find the app's ID, then try to install it using `mas install <id>`? Did that install properly?
