### ISSUE TITLE
`outdated` lists apps with no updates

### ISSUE THREAD

**Issue by fortin** [mas-cli/mas#497]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 13.4

### mas Install Method

`brew install mas` (homebrew-core)
- Xcode version: 14.3.1

## Describe the Bug

Instead of listing the apps with pending updates available, `mas outdated` returns:

```Warning: Identifier 1501342378 not found in store. Was expected to identify Classical.
1540160809 OneTab (1.57 -> 1.68)
1568262835 Super Agent (2.9.3 -> 2.9.4)
288545208 Instapaper (8.2.1 -> 8.3.1)
1136220934 Infuse (7.5.5 -> 7.5.6)
1365531024 1Blocker (4.1.13 -> 5.3.6)
409183694 Keynote (13.0 -> 13.1)
1346247457 Endel (4.29.2 -> 4.31)
899247664 TestFlight (3.3.0 -> 3.3.2)
1435957248 Drafts (39.1 -> 39.2)
```

None of these apps have pending updates in the App Store. The number of apps on that list has been increasing for the past few weeks.

The installed versions of those apps are the ones to the left of ->. 

## To Reproduce

All I need to do to reproduce it is run `mas outdated` and see if there are any updates available in the App Store, but YMMV.

## Expected Behavior

`mas outdated` should only display apps for which there are updates available in the App Store. 

## Actual Behavior

See above.

## Additional Context

> Did it work in a previous version?

No. I started using `mas` in March 2023, and came across this bug then.

**Comment by zyoshoka** [comment]
Duplicate of #491?

**Comment by fortin** [comment]
> Duplicate of #491?

Yes, missed that one. I'll close this.
