### ISSUE TITLE
Mas upgrade / outdated doesn't work

### ISSUE THREAD

**Issue by dm3ch** [mas-cli/mas#516]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): macOS 14.5 (23F79)

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug
When I try to call `mas outdated` or `mas upgrade` I'm getting:
```
Error: Unable to parse response JSON
```

> A clear and concise description of what the bug is.

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected Behavior

> A clear and concise description of what you expected to happen.

## Actual Behavior

> A clear and concise description of what actually happened.

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```bash
$ mas command
...
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

**Comment by dLeandroT** [comment]
I had the same error.
I reinstalled MAS and it works again 
`brew reinstall mas`

**Comment by dm3ch** [comment]
Hmm just tried to reproduce the problem before reinstall and I wasn't able to reproduce it anymore. Magic
