### ISSUE TITLE
Installed apps not found when running commands from Shortcuts app

### ISSUE THREAD

**Issue by LouisRoselli** [mas-cli/mas#532]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.1...
```shell
Software:

    System Software Overview:

      System Version: macOS 14.6.1 (23G93)
      Kernel Version: Darwin 23.6.0
      Time since boot: 5 days, 4 hours, 19 minutes
``` 

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

Running "mas" commands in Shortcuts app's "Run Shell Script" action is not detecting any installed apps on the system when running these commands:

| Command | Results |
|--------|--------|
| mas list | "No installed apps found" |
| mas outdated | *BLANK* |
| mas upgrade | "Warning: Nothing found to upgrade" |

- The Shortcuts app is running the script as Administrator and has permissions for Full Disk Access. (See screenshots attached)
- All commands work as expected and perfectly fine from Terminal. (See screenshots attached)

## To Reproduce

You can use this link to get a copy of the shortcut instead of manually creating one: https://www.icloud.com/shortcuts/25b3da7ce04b467bb75dc83dbd4b631c

1. Go to Shortcuts app.
2. Click on '+' at the top of the app to create a new shortcut.
3. In the shortcut, add an action called "Run Shell Script"
4. Set the following:
    1. ```shell
        PATH=$PATH:/opt/homebrew/bin
        mas list
        ``` 
    1. Shell: "zsh"
    1. Input: "Input"
    1. Pass Input: "to stdin"
    1. Run as Administrator: checked
5. Add an action called "Show Result" after the previous action and set the "Shell Script Result" as the output.
6. Repeat Steps 3-5 for commands "mas outdated" and "mas upgrade".

## Expected Behavior

> I expected a list of apps to show like the results from Terminal.
> I expected a list of outdated apps to show like the results from Terminal.
> I expected outdated apps to upgrade and show like the results from Terminal.

## Actual Behavior

> Got an output of "No installed apps found".
> Got an output of "".
> Got an output of "Warning: Nothing found to upgrade".

## Screenshots, Terminal Output
<img width="1196" alt="mas-shortcuts-issue-1" src="https://github.com/user-attachments/assets/1fccee52-aa5c-4c6a-92ac-79d9baf9422b">
<img width="1196" alt="mas-shortcuts-issue-2" src="https://github.com/user-attachments/assets/e62007bb-5d95-4a37-a53b-d40e43872572">
<img width="708" alt="mas-shortcuts-issue-3" src="https://github.com/user-attachments/assets/a1355936-3f75-407d-8ee1-feeafa1684f2">
<img width="559" alt="mas-shortcuts-issue-4" src="https://github.com/user-attachments/assets/2be5d9cc-0158-4c6f-8bf7-83e0bc62ba85">
<img width="559" alt="mas-shortcuts-issue-5" src="https://github.com/user-attachments/assets/9787edf7-d82b-47c6-84d2-9cf7348a0587">

**Comment by rgoldberg** [comment]
Uncheck `Run as Administrator`.

`sudo mas list`, not `mas list`,  is the same as `Run as Administrator`.

e.g.: 
```
$ sudo mas list
Password:
Error: No installed apps found

$ mas list
497799835   Xcode                     (14.2)
…
```

**Comment by LouisRoselli** [comment]
AND I'm dumb lol!  Unchecking the "Run as administrator" fixed it.  I think I originallly had it checked because of the full disk access permissions being weird.
