### ISSUE TITLE
`signin` fails over tmux

### ISSUE THREAD

**Issue by lanox** [mas-cli/mas#56]
Hi,

I seem to be having issues where mas thinks I am not signed in, however when I try signing in I get:

```console
$ mas signin xxxx@gmail.com
==> Signing in to Apple ID: xxxx@gmail.com
Password:
Error: Sign in failed: The operation couldn’t be completed. (mas.MASError error 1.)
```

And when I try installing with mas I get:

```console
$ mas install 715768417

Error: Not signed in

[ERROR] failed to install  715768417
```

Also if I open app store, I am showing as been signed in as I can download software and update.

Thanks.

**Comment by jutkko** [comment]
+1 for the issue.

**Comment by rodionovd** [comment]
Thanks for reporting this, @lanox! I'll see what can cause these problems as soon as possible

**Comment by rodionovd** [comment]
As a temporary workaround you can invoke the `signin` command with `--dialog` flag. This will open the Mac App Store application and ask to enter your password there:

```
$ mas signin --dialog my.apple.id@mail.com
```

**Comment by jutkko** [comment]
Just tried on my machine, the command is stuck here:

```
± |master U:1 ✗| → mas signin --dialog myemail@mail.com
==> Signing in to Apple ID: myemail@mail.com
```

And no Mac App Store is being launched.

**Comment by rodionovd** [comment]
Are you still on 10.11 or this happens on 10.12, @jutkko?

**Comment by lanox** [comment]
@rodionovd I have/had same symptom as @jutkko using ```-dialog``` will not work and nothing opens. I have tried this with mac os 10.11 and 10.12.

**Comment by rodionovd** [comment]
🤔 Interesting. I can't reproduce this on 10.12.1, but I'll setup a clean virtual machine tonight and see what's going on.

Just to be sure, `mas reset` doesn't help you either, @lanox, @jutkko?

**Comment by lanox** [comment]
@rodionovd mas reset does help but only for that run if I reset my mac or anything as such it won't work after.

**Comment by rodionovd** [comment]
@lanox thank you! From what I can tell, something appears to be broken on a Mac App Store's side because `reset` [just kills](https://github.com/mas-cli/mas/blob/master/mas-cli/Commands/Reset.swift#L16) a few MAS-related helper processes and that's it.

I can suggest removing all caches and preferences files for Mac App Store. I don't have a complete list of these right now, but I'll try to figure it out a bit later today and write here.

**Comment by lanox** [comment]
@rodionovd thanks for that.

**Comment by fycth** [comment]
Same issue:
- cli says 'mas.MASError error 1.'
- the '--dialog' option has no effect (nothing opens and it just stuck)
- the 'reset' option doesn't help

macOS 10.12.1

**Comment by mrzool** [comment]
Any update on this? I'm also unable to sign in.

`--dialog` opens up the GUI dialog and seems to work at first, but then fails with this error:

> An unexpected error occurred while signing in.
> AMD-Action:authenticate:SP

Running El Capitan 10.11.6.

**Comment by mrzool** [comment]
Now getting an error also when trying to sign in into the real App Store. Seems like some config file got messed up.

![signin](https://cloud.githubusercontent.com/assets/6874363/19896898/3314eb34-a056-11e6-800f-118d82be011f.png)

**Comment by cgardner** [comment]
I was getting the `Error: Sign in failed: The operation couldn’t be completed. (mas.MASError error 1.)` message.  It turned out that it was because I was trying to run mas in tmux.  The [README](https://github.com/mas-cli/mas#using-tmux) has documentation on how to resolve the problem if you're using tmux.

**Comment by lanox** [comment]
That also fixed it for me..

**Comment by awgeorge** [comment]
Not using TMUX - I'm getting this error - multiple machines, multiple accounts - looks like apple may have changed something? running macOS 10.12.2 (16C67) AppStore Version 2.2 (581.8)

**Comment by awgeorge** [comment]
Looks like it fails on accounts with two factor authentication setup.

It also fails when the account needs to switch stores:
<img width="422" alt="screen shot 2017-02-07 at 19 33 25" src="https://cloud.githubusercontent.com/assets/1777444/22718098/6fd4da12-ed6c-11e6-8dc5-8820ea161c02.png">

On a headless machine it seems to constantly fail - however on my laptop, while the error is returned in the console, the UI springs into action and performs the login regardless.

**Comment by Cloudef** [comment]
Have the same problem on freshly installed Sierra. Doesn't seem to work at all and have to resort for now manually installing programs from AppStore.

**Comment by Aghassi** [comment]
We may want to look to Fastlane for handling two factor auth

https://github.com/fastlane/fastlane/blob/60bac7e4a2a6c1e19d1cd20eb83201e7d0cb9e48/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L373

**Comment by heytxz** [comment]
@Aghassi Hi. When will mas-cli support the two factor auth of Apple ID？

**Comment by phatblat** [comment]
@awgeorge See #75. mas doesn't currently support switching store countries.

@heytxz See #163 for 2FA.
