### ISSUE TITLE
tmux support

### ISSUE THREAD

**Issue by shaneberg** [mas-cli/mas#57]
Most mas commands do not work inside of a tmux session. 

**Repro**
1. Open a terminal and observe that mas works correctly

`$ mas list`
2. Install tmux if needed

`$ brew install tmux`
3. Start new tmux session

`$ tmux new -smas-repro`
4. Run mas and observe different results

`$ mas list`

**Output**

```
$ mas list
No installed apps found
```

**Comment by rodionovd** [comment]
Thanks for reporting this, @seanhaneberg!

Have you tried the workaround listed [here](https://github.com/mas-cli/mas#using-tmux)?

**Comment by rodionovd** [comment]
OK, I'm closing this issue for now, but feel free to re-open it if the workaround doesn't work for you
