### ISSUE TITLE
Error updating Canva and CapCut

### ISSUE THREAD

**Issue by juanlazarde** [mas-cli/mas#582]
## Your Environment

- **mas Version**: 1.8.6
- **Operating System**: macOS
- **OS Version**: 15.0.1
- **Xcode Version**: 16.0 (16A242d)
- **Mac Model & Architecture**: Mac15,6 (MBP Pro M3)
- **Shell & Version**: zsh 5.9 (arm64-apple-darwin24.0)
- **Homebrew Version**: 4.4.1

### mas Install Method

`brew install mas` (homebrew-core)

## Describe the Bug

When updating apps with `mas upgrade`, both CapCut (ID: 1500855883, version 4.8.0 -> 12.9.0) and Canva (ID: 897446215, version 1.97.0 -> 4.131.0) appear to start and finish the update process successfully, yet they remain unchanged. This is evident as they reappear when running `mas outdated` or `mas upgrade` again, and their versions within the apps confirm this. 

## To Reproduce

1. Without Canva and/or CapCut installed. Run `mas install {897446215,1500855883}`, or install from App Store.
2. Run `mas upgrade` to attempt upgrading all apps.
3. Wait for the process to complete.
4. Run `mas outdated` to check for outdated apps.
5. Notice that CapCut and Canva are still listed as outdated, despite the upgrade seemingly completing successfully.

## Expected Behavior

`mas` should recognize that both apps are updated to the latest versions in App Store and no longer appear as outdated when running `mas outdated` or `mas upgrade`. Like all the other apps that did update.

## Actual Behavior

Despite running `mas upgrade`, both CapCut and Canva remain on their latest App Store versions, which do not align with the expected versions from `mas`.

## Screenshots, Terminal Output

<img width="433" alt="image" src="https://github.com/user-attachments/assets/e68a65bb-a485-4190-a54b-ec80ace0255e">

## Additional Context

I have also tried the following steps to fix the issue, but none have worked:
- Tried `mas uninstall 897446215` and deleted Canva from the **App Library**.
- Ran `mas install --force 897446215` to force update Canva.

**mas outdated** output:

```text
1500855883 CapCut (4.8.0 -> 12.9.0)
897446215 Canva (1.97.0 -> 4.131.0)
```

**mas list** output:

```text
6448461551 Command X (1.4.6)
1502839586 Hand Mirror (3.2)
1296084683 Cleaner for Xcode (4.0.6)
553245401 Friendly Streaming (5.9.68)
1278508951 Trello (2.15.2)
1545870783 Color Picker (2.0.3)
441258766 Magnet (3.0.2)
6444667067 Hyperduck (1.2.1)
450527929 djay Pro (5.2.4)
897446215 Canva (1.97.0)
600925318 Parallels Client (19.4.25221)
1451685025 WireGuard (1.0.16)
497799835 Xcode (16.0)
1556313108 Scan Thing (1.1)
1522267256 Shareful (1.10.3)
1668083311 Whisper Transcription (10.3.2)
1355679052 Dropover (4.15.2)
1037126344 Apple Configurator (2.17)
1607635845 Velja (2.0.6)
803453959 Slack (4.40.133)
1500855883 CapCut (4.8.0)
1518425043 Boop (1.4.0)
```

**Workaround**:  

Just ignore it. But, the downside is that `mas` unnecessarily downloads and re-installs the app. Wasting time, space, and bandwith.

**Proposed Solutions**:

1. Of course, fix the version in the index/repository, e.g., Canva's latest version is 1.97.0, not 4.131.0.
2. Create an exclusion option: `mas upgrade --exclude  897446215` for users to use as workarounds or customize install.
3. After confirming that a new `mas outdated` is not blank, add these apps to an exclusion list. Then provide the option to ignore, e.g., `mas upgrade --exclusion-list`. Perhaps automatically submit a ticket for the repo's admin to review and take proper action.

**Kudos!**

Thank you, @rgoldberg, for your engagement and hard work in advancing this project. Following your suggestion, I moved this issue from #512 and separated it from the beta installation, as I believe they are unrelated. I don’t see it as a major issue (beta or not); it appears to stem from the index where MAS retrieves the latest versions. However, this presents an opportunity to address it programmatically.

**Comment by rgoldberg** [comment]
Sorry, there's been a miscommunication. The problem that you're describing here was identified in #491, #336 & other duplicate issues; it was fixed by PR #496.

That PR has been merged into the `main` branch on GitHub. It is also in the `v1.8.7-beta.35` tagged release. It is not, however, in any non-beta release.

The issue I was trying to investigate is the `Error: Search failed` from this part of [your comment](https://github.com/mas-cli/mas/issues/512#issuecomment-2420338043) about `v1.8.7-beta.35`:

> Hello, unsure where to post this. I’ve installed the latest beta version of mas-cli using:
> 
> curl -L -o mas.pkg https://github.com/mas-cli/mas/releases/download/v1.8.7-beta.35/mas.pkg
> sudo installer -pkg mas.pkg -target /
> 
> After installation, the mas version confirms as 1.8.7-beta.35.
> 
> But, when I run `mas outdated` or `mas upgrade`, I get `Error: Search failed`. Yet, I can install new packages (e.g., `mas install <some package>`).

Have you tried the `main` version of mas? If so, did it also output `Error: Search failed` on your machine?

**Comment by juanlazarde** [comment]
Got it. There's an error during the `main` install.

## Steps:
1. `brew uninstall mas` (ver. 1.8.6)
2. `brew install --HEAD mas`

## Output with error:
```==> script/build
Last 15 lines from /Users/juan/Library/Logs/Homebrew/mas/01.build:
Working copy of https://github.com/apple/swift-argument-parser.git resolved at 1.5.0
Creating working copy for https://github.com/Quick/Nimble.git
Working copy of https://github.com/Quick/Nimble.git resolved at 13.6.0
Creating working copy for https://github.com/apple/swift-algorithms.git
Working copy of https://github.com/apple/swift-algorithms.git resolved at 1.2.0
Creating working copy for https://github.com/mattgallagher/CwlPreconditionTesting.git
Working copy of https://github.com/mattgallagher/CwlPreconditionTesting.git resolved at 2.2.2
Creating working copy for https://github.com/mattgallagher/CwlCatchException.git
Working copy of https://github.com/mattgallagher/CwlCatchException.git resolved at 2.2.1
warning: 'quick': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /private/tmp/mas-20241018-2755-fwl20o/.build/checkouts/Quick/Sources/Quick/PrivacyInfo.xcprivacy
warning: 'nimble': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /private/tmp/mas-20241018-2755-fwl20o/.build/checkouts/Nimble/Sources/Nimble/PrivacyInfo.xcprivacy
error: the test 'masTests' requires macos 10.13, but depends on the product 'Nimble' which requires macos 10.15; consider changing the test 'masTests' to require macos 10.15 or later, or the product 'Nimble' to require macos 10.13 or earlier.
error: the test 'masTests' requires macos 10.13, but depends on the product 'Quick' which requires macos 10.15; consider changing the test 'masTests' to require macos 10.15 or later, or the product 'Quick' to require macos 10.13 or earlier.
```

## Snapshot
<img width="999" alt="image" src="https://github.com/user-attachments/assets/56796113-b6c9-407b-8bb6-84000c623046">

**Comment by rgoldberg** [comment]
That is an easy fix. I'll downgrade Nimble & Quick. The newer Xcode is more stringent about testing library macOS version requirements than my version of Xcode.

**Comment by rgoldberg** [comment]
@juanlazarde I've downgraded both Nimble & Quick in `main`, so please try `brew install --HEAD mas` again.

**Comment by juanlazarde** [comment]
@rgoldberg It worked like a charm. Thanks!
> Version 1.8.7-beta.8

## Snapshot
<img width="775" alt="image" src="https://github.com/user-attachments/assets/7bd617f4-6ca7-44d1-8e51-d67356064a43">

**Comment by rgoldberg** [comment]
@juanlazarde Thanks. I do not know why the beta failed for you, since it worked for me, but it's good that `main` is working for you.

Hopefully, all the fixes in `main` will be released within a month.

Subscribe to the other issue you originally commented on to see when it closes, as we should have a new release then, so you'll be able to switch off of `main`, back to the normal mas Homebrew formula.
