### ISSUE TITLE
`list` doesn't output installed apps

### ISSUE THREAD

**Issue by trevordmiller** [mas-cli/mas#61]
When I run `mas list` I get no output, even though I have a few Mac app store apps installed:
![image](https://cloud.githubusercontent.com/assets/5497885/19841763/dbe1971c-9ed5-11e6-9340-72c8dd00f87f.png)

However, other `mas` commands work like `mas upgrade` and `mas search`:
![image](https://cloud.githubusercontent.com/assets/5497885/19841771/f04fa964-9ed5-11e6-9d23-628a43284218.png)

Is it required that I download apps with `mas install` for them to show up with `mas list`? If not, this may be an issue with Mac Sierra which I am on.

**Comment by rodionovd** [comment]
Thanks for getting in touch, @trevordmiller!

Can you please, run `mas reset` and try again (you'll need to sign in again)?

**Comment by trevordmiller** [comment]
![image](https://cloud.githubusercontent.com/assets/5497885/19869747/3d27e042-9f73-11e6-978f-9f28ac8a77c1.png)

That did the trick. Thank you!
