### ISSUE TITLE
Display price in search [Enhancement]

### ISSUE THREAD

**Issue by lukaskollmer** [mas-cli/mas#62]
(Related to #60)

As of right now, search results look like this:

```
$ mas search Tweetbot
557168941 Tweetbot for Twitter
```

I think search results should display the price of an app as well, like this: 

```
$ mas search Tweetbot
> 557168941 ($9.99) Tweetbot for Twitter
```

**Comment by Ixohoxi** [comment]
I think that would be useful, definitely. Perhaps such information should require a CLI switch, "--price" for example. Going further, it would be nice if such pricing information were decimal-aligned. And even further, a switch to "--round" the price to the nearest dollar.

**Comment by phatblat** [comment]
Added in #148. This will be in 1.4.2
