### ISSUE TITLE
Custom Homebrew tap has incorrect versions in bottle URLs

### ISSUE THREAD

**Issue by antoine2711** [mas-cli/mas#634]
## Your Environment

- `mas version`: latest?
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.15.7

### mas Install Method

- `brew install mas-cli/tap/mas`
- Xcode version: 12.4

## To Reproduce

1. Type in the terminal: `brew install mas-cli/tap/mas`

## Expected Behavior

Not to stop the installation process.

## Actual Behavior

Stops.

## Screenshots, Terminal Output

```bash
dominique$ brew install mas-cli/tap/mas
Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching mas-cli/tap/mas
==> Downloading https://github.com/mas-cli/mas/releases/download/v1.8.7-beta.1/mas-1.8.7-beta.40.catalina.bottle.tar.gz
##O#-  #                                                                                                               
curl: (22) The requested URL returned error: 404 
Error: mas: Failed to download resource "mas"
Download failed: https://github.com/mas-cli/mas/releases/download/v1.8.7-beta.1/mas-1.8.7-beta.40.catalina.bottle.tar.gz
```

**Comment by rgoldberg** [comment]
@antoine2711 Thanks. Will investigate.

**Comment by rgoldberg** [comment]
@antoine2711 There are a few issues in the new release procedure.

@phatblat Can you investigate?

**Comment by rgoldberg** [comment]
@antoine2711 mas 1.8.8 was released.

The [Homebrew custom tap](https://github.com/mas-cli/homebrew-tap) now provides correct platform-specific binaries for both `arm64` & `x86_64`.

The `.pkg` installer from the [GitHub Release](https://github.com/mas-cli/mas/releases/v1.8.8) installs a Universal 2 binary.
