### ISSUE TITLE
1.8.7 GitHub Release & Homebrew custom tap binaries are arm64 instead of universal

### ISSUE THREAD

**Issue by kiryanov** [mas-cli/mas#635]
mas binary in all of the 1.8.7 release files only contains arm64 architecture. x86_64 is missing completely. The last version that works is 1.8.7-beta.43

### Working version
$ ./mas version
1.8.7-beta.43
$ file mas
mas: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64]
mas (for architecture x86_64):	Mach-O 64-bit executable x86_64
mas (for architecture arm64):	Mach-O 64-bit executable arm64

### Non-working version (1.8.7 release)
$ ./mas version
./mas: Bad CPU type in executable
$ file mas
mas: Mach-O 64-bit executable arm64

**Comment by rgoldberg** [comment]
This build issue should now be fixed in our release process, but waiting for the person who revamped the release process to have free time to verify, and to fix another issue.

**Comment by rgoldberg** [comment]
@kiryanov mas 1.8.8 was released.

The [Homebrew custom tap](https://github.com/mas-cli/homebrew-tap) now provides correct platform-specific binaries for both `arm64` & `x86_64`.

The `.pkg` installer from the [GitHub Release](https://github.com/mas-cli/mas/releases/v1.8.8) installs a Universal 2 binary.

**Comment by kiryanov** [comment]
Problem solved, thanks a lot!
