### ISSUE TITLE
mas doesn't support iPad or iPhone apps

### ISSUE THREAD

**Issue by georgettica** [mas-cli/mas#648]
## Your Environment

mas version:

1.8.7
macOS version:

ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91

### mas Install Method

[x] `brew install mas` ([Homebrew core](https://github.com/Homebrew/homebrew-core))

[] `brew install mas-cli/tap/mas` ([mas Homebrew custom tap](https://github.com/mas-cli/homebrew-tap))

[] [mas GitHub Releases](https://github.com/mas-cli/mas/releases)

- URL of the installer:

[] Built from source

- git origin URL: \<e.g., GitHub fork URL, <https://github.com/mas-cli/mas>…\>
- git revision:
- git tag/branch:
- Xcode version:

## Bug Description

I expect the fact that IPMIView is not a normal app store app and is wrapped, which creates this issue.

ie - the `Contents/Info.plist` is at `Wrapped/${appname}.app/Info.plist` 

## Steps to Reproduce

1. add IPMIView app
2. wait for the update to show up
3. run `mas update` or  any `mas` command and see it is not expected

## Expected Behavior
that a wrapped app store app will act like any other.

## Shell Output, Screenshots…

\<copy & paste shell commands & output below\>

```shell
$ mas <command> …
…
```

\<attach screenshots only if cannot copy & paste\>

## Additional Context

\<e.g., did the bug occur in previous mas or macOS versions?>

**Comment by rgoldberg** [comment]
I have no idea what the issue is.

Neither the bug description nor "see it is not expected" indicate what is not working properly.

What is the actual behavior that is occurring?

What is the expected behavior that isn't occurring?

Can you provide commands like `mas install <app-id>` in steps to reproduce, because there could be multiple apps with the same or similar names.

**Comment by rgoldberg** [comment]
@georgettica I have no idea what issue you are trying to report.

Can you provide steps to reproduce, including commands like `mas install <app-id>` because there could be multiple apps with the same or similar names.

What is the actual behavior that is occurring?

What is the expected behavior that isn't occurring?

**Comment by rgoldberg** [comment]
@georgettica please provide output of:

```shell
mas list
mas outdated
mas upgrade
```

What version of the app is actually installed (according to its "About <app name>" menu item)?

What version does the Mac App Store GUI report as the current version?

What region Mac App Store GUI are you using?

What region is your Mac using (from System Settings)?

**Comment by rgoldberg** [comment]
It's most likely because does mas not support iPadOS or iOS apps.

I use an Intel, so I cannot test this myself. I can try to look through the code in a bit. Are any of the other listed apps also iPadOS apps?

Are all wrapped apps either iOS or iPadOS, and vice versa?

**Comment by rgoldberg** [comment]
@georgettica Please also run the following from your command line & reply with the results:

```shell
mdfind 'kMDItemAppStoreAdamID == 952163566'
```

**Comment by rgoldberg** [comment]
@georgettica Thanks for running the command line.

It would be very difficult to investigate this enough to implement iOS & iPadOS app support without me having direct control of an Apple Silicon Mac.

It's probably easiest for me to wait to implement this until I get an Apple Silicon Mac, which should be this upcoming summer. I might be able to borrow a friend's machine before then.

Sorry to make you & others wait for this.

**Comment by rgoldberg** [comment]
@georgettica Can you run the following command?

```shell
mdls '/Applications/IPMIView.app'
```

If `/Applications/IPMIView.app` isn't the path to the IPMIView, please replace it with the correct path to whatever contains the `Wrapped/${appname}.app/Info.plist` that you mentioned in the original issue description.

**Comment by rgoldberg** [comment]
@Accademia The lack of `952163566 ` & of a property named `kMDItemAppStoreAdamID` in the Spotlight output does not bode amazingly well for for supporting iPadOS & iOS apps.

Looks like mas might need to supper bundle IDs instead of app IDs (#541).

**Comment by rgoldberg** [comment]
@georgettica See https://github.com/mas-cli/mas/issues/669#issuecomment-2536045376

Will track work in #321. Will leave this issue open for now, but probably won't get to all this for a few months at earliest, but probably later.
