### ISSUE TITLE
Cannot update iTunes

### ISSUE THREAD

**Issue by sofaking** [mas-cli/mas#65]
Don't see iTunes in the outdated list and thus cannot update it. I'm currently have iTunes 12.5.1 and AppStore suggests to update it to 12.5.2.

I guess this is somehow related to the fact that I actually didn't get iTunes via AppStore, it was rather preinstalled. But I couldn't find any info about that in docs or issues, so I wonder if this is true.

FYI, mas version: 1.3.1, macOS: 10.12.1

**Comment by rodionovd** [comment]
> I guess this is somehow related to the fact that I actually didn't get iTunes via AppStore, it was rather preinstalled. 

You're quite right @sofaking: `mas` is only able to install applications that are listed in Mac App Store itself. Please see this https://github.com/mas-cli/mas/issues/58#issuecomment-257074662 for more information and workarounds.

Thanks!
