### ISSUE TITLE
many app id's are unavailable 

### ISSUE THREAD

**Issue by tb-Ajaygandikota** [mas-cli/mas#659]
### mas version

1.8.7

### macOS version

15.1.1

### macOS build version

24B2091

### mas installation method

Homebrew core (brew install mas)

### Expected behavior

it should give same appids as in appstore

### Actual behavior

app id'd collected from app search are not available 

for example:-
 the ms word id show in mas search is 586447913 and in actual it is 462054704

### Steps to reproduce

```shell

```

**Comment by rgoldberg** [comment]
@tb-Ajaygandikota Using mas 1.8.7 installed from Homebrew core, I get the correct app ID for Word:

```shell
$ mas search word
   409201541  Pages                           (14.2)
   462054704  Microsoft Word                  (16.91)
   …
```

Are you using Apple Silicon or Intel?

I'm using Intel.

What region Mac App Store are you using (click on <your name> in bottom left, then Account Settings in top right, Country/Region)?

What region is your Mac set to use in general (from System Settings)?

Both my settings are for the US.

**Comment by tb-Ajaygandikota** [comment]
hi @rgoldberg , thanks for the reply 
I'm actually working on apple silicon, and the region is India for both app store and general settings.

is it an issue due to region ??

**Comment by rgoldberg** [comment]
Possibly. I'm not sure. Can you try setting both settings to US to see if that makes a difference for your `mas search word`?

**Comment by rgoldberg** [comment]
And can you supply the actual command line you run plus its results?

**Comment by rgoldberg** [comment]
@tb-Ajaygandikota mas doesn't store any info. It obtains info from Apple frameworks on the Mac or from Apple web APIs.

App IDs shouldn't change for an app.

A company might have a separate "app" for different major versions of an app, but they would be considered distinct apps, each with a consistent ID.

I tried to search the India Mac App Store using:

```
https://itunes.apple.com/lookup?media=software&entity=desktopSoftware&country=in&id=586447913
```

But got no results. So I'm not sure why you're seeing that app ID in your search results.

Does everything look good now?

If so, I'll close this issue.

Thanks.

**Comment by tb-Ajaygandikota** [comment]
yeah sure @rgoldberg you can close this thanks for the info.
