### ISSUE TITLE
mas doesn't support iPad or iPhone apps

### ISSUE THREAD

**Issue by Accademia** [mas-cli/mas#669]
### mas version

v1.8.8-beta.13

### macOS version

15.1.1

### macOS build version

24B91

### Processor

Apple M3 Max

### mas installation method

Homebrew core (brew install mas)

### Expected behavior

The latest version of Mas seems unable to update iPad apps in the App Store, such as “Xiaohongshu.”
https://apps.apple.com/us/app/%E5%B0%8F%E7%BA%A2%E4%B9%A6/id741292507

### Actual behavior

After executing "mas upgrade" , it did not detect that this app needed to be updated.

### Steps to reproduce

```console

```

**Comment by rgoldberg** [comment]
@Accademia mas doesn't yet support iPad or iPhone apps. The feature request is #321.

I have an Intel Mac, so I cannot investigate or implement this now.

Can you run the following Terminal command so I can learn where iPad apps are stored on the file system?

```shell
mdfind 'kMDItemAppStoreAdamID == 741292507'
```

Thanks.

**Comment by Accademia** [comment]
> @Accademia mas doesn't yet support iPad or iPhone apps. The feature request is #321.
> 
> I have an Intel Mac, so I cannot investigate or implement this now.
> 
> Can you run the following Terminal command so I can learn where iPad apps are stored on the file system?
> 
> ```shell
> mdfind 'kMDItemAppStoreAdamID == 741292507'
> ```
> 
> Thanks.

Thank you very much for your response.

Regarding your command line (mdfind 'kMDItemAppStoreAdamID == 741292507'),

there was no execution result on my computer, as shown in the screenshot.

![longshot20241209065846](https://github.com/user-attachments/assets/c62a5775-6158-4bf5-b8a5-8cbaa29fd89c)


If possible, I can execute more commands to help you explore whether this functionality is feasible enough to implement.

**Comment by rgoldberg** [comment]
@Accademia Thanks for the offer of help. I assume it will be possible to implement, but it won't be feasible to implement without me directly using an Apple Silicon machine.

The tentative plan is to get to it during summer of 2025. The good news is that there are many other planned improvements for mas that I can work on beforehand, so people will get other features & bug fixes in the meantime.

**Comment by rgoldberg** [comment]
@Accademia Can you run the following command?

```shell
mdls '/Applications/Xiaohongshu.app'
```

If `/Applications/Xiaohongshu.app` isn't the path to the app that you mentioned, please replace it with the correct path to it. You can probably just look for the app under `/Applications/`. If it's not under `/Applications/`, I'm not exactly sure where it would be.

**Comment by Accademia** [comment]
Thank you very much for your reply and for the task you assigned me. I have executed the command, as shown in the image.

![longshot20241210032928](https://github.com/user-attachments/assets/70964440-6035-430d-b86a-169a61666b2f)

It is important to note that Xiaohongshu (in English) is translated as “小红书” in Chinese. Since my system is in Chinese, it is displayed and queried in Chinese on my system.

xiaohongshu.app = 小红书.app

If there is anything else you need me to do, please let me know.

**Comment by Accademia** [comment]
Thank you very much for your reply and for the task you assigned me. I have executed the command, as shown in the image.

![longshot20241210054207](https://github.com/user-attachments/assets/96bc2b2a-7da2-4159-bfe4-4d33a4ce057a)

It is important to note that Xiaohongshu (in English) is translated as “小红书” in Chinese. Since my system is in Chinese, it is displayed and queried in Chinese on my system.

xiaohongshu.app = 小红书.app (Chinese MacOS)

If there is anything else you need me to do, please let me know.

**Comment by Accademia** [comment]
> @Accademia Can you run the following command?
> 
> ```shell
> mdls '/Applications/Xiaohongshu.app'
> ```
> 
> If `/Applications/Xiaohongshu.app` isn't the path to the app that you mentioned, please replace it with the correct path to it. You can probably just look for the app under `/Applications/`. If it's not under `/Applications/`, I'm not exactly sure where it would be.

Thank you very much for your reply and for the task you assigned me. I have executed the command, as shown in the image.

![longshot20241210054207](https://github.com/user-attachments/assets/cea6587d-41d7-43df-b59c-4110d43ce6a5)


It is important to note that Xiaohongshu (in English) is translated as “小红书” in Chinese. Since my system is in Chinese, it is displayed and queried in Chinese on my system.

xiaohongshu.app = 小红书.app (Chinese MacOS)

If there is anything else you need me to do, please let me know.

**Comment by rgoldberg** [comment]
@Accademia Thanks for the info.

Is there any way you can copy & paste the output instead of posting a screenshot?

That will make it easier to work with.

**Comment by rgoldberg** [comment]
@Accademia The lack of `741292507` & of a property named `kMDItemAppStoreAdamID` in the Spotlight output does not bode amazingly well for for supporting iPadOS & iOS apps. Looks like mas might need to supper bundle IDs instead of app IDs (#541).

**Comment by Accademia** [comment]
> @Accademia Thanks for the info.
> 
> Is there any way you can copy & paste the output instead of posting a screenshot?
> 
> That will make it easier to work with.

Okay, I’ll provide a few more examples of iPadOS apps.

Delat - Game Emulator （https://apps.apple.com/us/app/delta-game-emulator/id1048524688）

```
MacBook-Pro-M3 ~ % mdls '/Applications/delta.app'
_kMDItemDisplayNameWithExtensions  = "Delta.app"
kMDItemAlternateNames              = (
    "Delta.app"
)
kMDItemAppStoreHasMetadataPlist    = 1
kMDItemCFBundleIdentifier          = "com.rileytestut.Delta"
kMDItemContentCreationDate         = 2024-09-19 23:12:35 +0000
kMDItemContentCreationDate_Ranking = 2024-09-19 00:00:00 +0000
kMDItemContentModificationDate     = 2024-09-19 23:12:35 +0000
kMDItemContentType                 = "com.apple.application-bundle"
kMDItemContentTypeTree             = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)
kMDItemCopyright                   = ""
kMDItemDateAdded                   = 2024-11-19 20:54:47 +0000
kMDItemDescription                 = ""
kMDItemDisplayName                 = "Delta.app"
kMDItemDocumentIdentifier          = 0
kMDItemExecutableArchitectures     = (
    arm64
)
kMDItemExecutablePlatform          = "LSRequiresIPhoneOS"
kMDItemFSContentChangeDate         = 2024-09-19 23:12:35 +0000
kMDItemFSCreationDate              = 2024-09-19 23:12:35 +0000
kMDItemFSCreatorCode               = ""
kMDItemFSFinderFlags               = 0
kMDItemFSHasCustomIcon             = (null)
kMDItemFSInvisible                 = 0
kMDItemFSIsExtensionHidden         = 1
kMDItemFSIsStationery              = (null)
kMDItemFSLabel                     = 0
kMDItemFSName                      = "Delta.app"
kMDItemFSNodeCount                 = 2
kMDItemFSOwnerGroupID              = 0
kMDItemFSOwnerUserID               = 0
kMDItemFSSize                      = 104005457
kMDItemFSTypeCode                  = ""
kMDItemInterestingDate_Ranking     = 2024-09-19 00:00:00 +0000
kMDItemKeywords                    = ""
kMDItemKind                        = "应用程序"
kMDItemLogicalSize                 = 104005457
kMDItemPhysicalSize                = 104505344
kMDItemVersion                     = "1.6.8"
```

------

XiaoHongShu （小红书 - 你的生活指南）
Link 1 ：https://apps.apple.com/us/app/%E5%B0%8F%E7%BA%A2%E4%B9%A6-%E4%BD%A0%E7%9A%84%E7%94%9F%E6%B4%BB%E6%8C%87%E5%8D%97/id741292507
Link 2 ： https://apps.apple.com/us/app/xiaohongshu/id741292507

Note: Link1 and Link2 point to the same App Store app, but one uses a URL with Chinese characters, while the other uses a URL with English characters.

```
MacBook-Pro-M3 ~ % mdls '/Applications/小红书.app'
_kMDItemDisplayNameWithExtensions           = "小红书.app"
_kMDItemRecentOutOfSpotlightEngagementDates = (
    "2024-11-26 07:19:23 +0000",
    "2024-11-26 07:19:42 +0000",
    "2024-11-26 07:20:14 +0000",
    "2024-11-26 07:20:27 +0000"
)
kMDItemAlternateNames                       = (
    "\U5c0f\U7ea2\U4e66.app"
)
kMDItemAppStoreHasMetadataPlist             = 1
kMDItemCFBundleIdentifier                   = "com.xingin.discover"
kMDItemContentCreationDate                  = 2024-12-07 19:13:45 +0000
kMDItemContentCreationDate_Ranking          = 2024-12-07 00:00:00 +0000
kMDItemContentModificationDate              = 2024-12-07 19:13:45 +0000
kMDItemContentType                          = "com.apple.application-bundle"
kMDItemContentTypeTree                      = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)
kMDItemCopyright                            = ""
kMDItemDateAdded                            = 2024-11-19 20:54:49 +0000
kMDItemDescription                          = ""
kMDItemDisplayName                          = "小红书.app"
kMDItemDocumentIdentifier                   = 0
kMDItemExecutableArchitectures              = (
    arm64
)
kMDItemExecutablePlatform                   = "LSRequiresIPhoneOS"
kMDItemFSContentChangeDate                  = 2024-12-07 19:13:45 +0000
kMDItemFSCreationDate                       = 2024-12-07 19:13:45 +0000
kMDItemFSCreatorCode                        = ""
kMDItemFSFinderFlags                        = 0
kMDItemFSHasCustomIcon                      = (null)
kMDItemFSInvisible                          = 0
kMDItemFSIsExtensionHidden                  = 1
kMDItemFSIsStationery                       = (null)
kMDItemFSLabel                              = 0
kMDItemFSName                               = "小红书.app"
kMDItemFSNodeCount                          = 2
kMDItemFSOwnerGroupID                       = 0
kMDItemFSOwnerUserID                        = 0
kMDItemFSSize                               = 387291322
kMDItemFSTypeCode                           = ""
kMDItemInterestingDate_Ranking              = 2024-12-07 00:00:00 +0000
kMDItemKeywords                             = " 小红薯,分享, 小红书, 穿搭, xhs, 社交, xiaohongshu, 美妆"
kMDItemKind                               = "应用程序"
kMDItemLastUsedDate                         = 2024-11-26 07:20:27 +0000
kMDItemLastUsedDate_Ranking                 = 2024-11-26 00:00:00 +0000
kMDItemLogicalSize                          = 387291322
kMDItemPhysicalSize                         = 390729728
kMDItemUseCount                             = 5
kMDItemUsedDates                            = (
    "2024-11-25 16:00:00 +0000"
)
kMDItemVersion                              = "8.65"
```

SirIf there is anything else I can do, please let me know. Thank you very much.

**Comment by rgoldberg** [comment]
@Accademia Thanks for the additional output.

Looks like we might need to use another data source for installed iOS & iPadOS apps.

We can look for other data sources (dependent on #565).

Assuming that there are no other useful data sources, and that the known data sources behave as I suspect from the info I've seen, mas can:

- find installed apps via Spotlight instead of via `CKSoftwareMap`
- encourage users to use bundle IDs instead of app IDs (see #541)
- use the iTunes Search API to map between bundle ID & app ID as necessary

Will track work in #321. Will leave this issue open for now, but probably won't get to all this for a few months at earliest, but probably later.

**Comment by rgoldberg** [comment]
See #321
