### ISSUE TITLE
Remove `Distribution.plist`; replace with a heredoc / process substitution in `script/package`

### ISSUE THREAD

**Issue by rgoldberg** [mas-cli/mas#677]
Remove `Distribution.plist`; replace a with heredoc / process substitution in `script/package`.

**Comment by phatblat** [comment]
The [`Distribution.plist`](https://github.com/mas-cli/mas/blob/main/Package/Distribution.plist) file is the config for generating the macOS installer `.pkg`. Is there a newer way to build them?

**Comment by rgoldberg** [comment]
@phatblat The idea was just to use process substitution (probably a file-based `=(printf …)`, but pipe-based`<(printf …)`, if the latter will work) to provide the content from [Distribution.plist](https://github.com/mas-cli/mas/blob/main/Package/Distribution.plist) to the `productbuild` call in `script/package`, so the details are in the script & we don't have a file sitting in git that's only used in one place.

**Comment by phatblat** [comment]
Ah, that's a good idea. It can just be a heredoc input in a script.

**Comment by rgoldberg** [comment]
Resolved by #640.
