### ISSUE TITLE
Add the ability to install programs from a list

### ISSUE THREAD

**Issue by danielcompton** [mas-cli/mas#68]
When bootstrapping a new computer, I need to go to the Mac App Store to download the apps I need from there. It would be great if I could maintain a list of apps to install via `mas list`, and then run something like `mas install mas-apps.txt` on a new computer to ensure that all required apps are installed.

**Comment by danielcompton** [comment]
Ah, didn't see #21.

**Comment by rodionovd** [comment]
Hello Daniel!

Since `mas install` supports multiple arguments you can do something like this:

```
$ cat mas_apps.txt
>1024069033
>452840086

$ mas install $(cat mas_apps.txt)
```

**Comment by danielcompton** [comment]
Thanks! My underlying question was about integrating with Homebrew bundle, so seeing that Homebrew has direct integration now is perfect. 👍

**Comment by AlexanderWillner** [comment]
For reference for the same use case without using brew (would be nice to use ```mas list``` with a specific option to show only IDs though):
```
# save list of installed apps
mas list|sed '1d'|awk '{print $1}' > list-mas.txt
# install apps again
cat list-mas.txt|xargs mas install
```
