### ISSUE TITLE
"Error switching storefront" when signing in

### ISSUE THREAD

**Issue by cybertk** [mas-cli/mas#7]
When sign in on Travis, **mas signin** is failed with exit code 6 and with message **Error switching storefront**, see https://travis-ci.org/cybertk/vagrant-box-osx#L257.

But actually, **mas signin** is succeed as **mas account** returns valid account.

**Comment by argon** [comment]
I think this is valid behaviour with the error. I will try to investigate what caused it but I have seen it before using the regular App so I don't think there's much I can do.

It's probably related to switching region

**Comment by cybertk** [comment]
I think **mas** should exit with 0 in this case. Maybe **mas** should fail only when both `ISStoreAccount.primaryAccount == nil` and `ISStoreAccount.signIn` throwing errors

**Comment by argon** [comment]
If the primary account matches the login details then that is a good idea. If you want to make a PR I can take a look

**Comment by phatblat** [comment]
@cybertk is this issue still relevant with mas 1.3.1?
