### ISSUE TITLE
Safety/Stability discussion

### ISSUE THREAD

**Issue by nidegen** [mas-cli/mas#73]
As it is neither an official API nor officially supported, I wonder how you generally think of the safety using mas-cli/mas.

Does anyone know if some mas devs at apple are following/supporting this project undercover?

**Comment by rodionovd** [comment]
Hi Nicolas, thanks for getting in touch!

> I wonder how you generally think of the safety using mas-cli/mas.

`mas` is built on top of the same frameworks/libraries as Mac App Store.app itself, so it's *at least* as reliable (sometimes even [more](https://twitter.com/lnwdr/status/793023421672198146) reliable 😄).

> Doesw anyone know if some mas devs at apple are following/supporting this project undercover?

Of course it's not officially supported by Apple (they don't even care about the MAS app actually), but we try to keep `mas` in a good shape by updating it whenever a new version of macOS is out.

It's also open source, so you can check the code yourself :-)

**Comment by nidegen** [comment]
cool! so you are saying that the api is absolutely safe to use? i didnt dig into the code too deep, but remembered reading somewhere that the api was reverse-engineered or similar once.

anyways, the tool is awesome, thanks for maintaining it!

**Comment by rodionovd** [comment]
> so you are saying that the api is absolutely safe to use?

I'm not sure what you mean here, but if you trust Mac App Store.app then there's no reason you shouldn't trust `mas`.

> remembered reading somewhere that the api was reverse-engineered or similar once.

Sure, these frameworks (libraries) I mentioned above — they're *private* (read, Apple don't want anyone else to use them), so there's no documentation/examples/etc. This is why we have to reverse-engineer these libraries to figure out what they're capable of and how they work

**Comment by timsutton** [comment]
Any use of private APIs means the behaviour is subject to change without notice. That said, I'm not sure this project has ever needed to make any major changes _so far_ to accommodate framework changes in a new minor or major OS release from Apple.

That is almost guaranteed to be required at some point in the future, but unless you work for Apple on these particular frameworks the timeframe for that is unknown. It could be in three months, five years, or...

**Comment by nidegen** [comment]
ok. that is what i meant. but also, you can not be sure of missing some intilizations or so that my leave some traces in the AppStore.app maybe. right?

 so CommerceKit and StoreFoundation headers were extracted from the compiled macOS libs? so they at least match the apple-internal frameworks?

**Comment by rodionovd** [comment]
> That is almost guaranteed to be required at some point in the future

This is true and we're ready to accommodate any changes in the future :-)

**Comment by rodionovd** [comment]
> so CommerceKit and StoreFoundation headers were extracted from the compiled macOS libs? so they at least match the apple-internal frameworks?

They are *exact* representation of Apple's internal frameworks ;)

**Comment by nidegen** [comment]
OK, now I am happy:D thanks for your explanations:)
