### ISSUE TITLE
Purchase incompatible apps

### ISSUE THREAD

**Issue by poweruser82** [mas-cli/mas#74]
I don't know if my request is feasible.
I'm running OS X 10.10.5, I would like to be able to buy apps which requires OS X 10.11 or newer.
I don't care if they can't run. I just want to purchase them at the moment so I can install them in the future when I have a compatible mac.

**Comment by rodionovd** [comment]
Hello @poweruser82, thanks for your request.

Unfortunately, `mas` is unable to *purchase* applications so this feature could not be implemented.
