### ISSUE TITLE
App IDs changing?

### ISSUE THREAD

**Issue by mwean** [mas-cli/mas#77]
I exported a list of apps (using `mas list`) to install on a new machine a couple weeks ago. I went to install them today, and several of them failed. I did `mas list` again on the old machine and found that for the ones that failed to install, their IDs were now one higher (e.g. 455545699 → 455545700). Has anyone else seen this? Are the IDs maybe version-specific?

**Comment by rodionovd** [comment]
Hello Matt! Thanks for your question.

>  Has anyone else seen this? Are the IDs maybe version-specific?

This is not something I'm aware of. Looks like a bug to me. Would be great if you still have the list of the failed app ids, so we can figure it out?

Thanks!

**Comment by mwean** [comment]
These are the ones that changed:

```
BitPerfect:             455545699 => 455545700
Quiver:                 866773893 => 866773894
I Love Stars:           402642759 => 402642760
FruitJuice:             671736911 => 671736912
Monosnap:               540348654 => 540348655
Tomatoes:               545957563 => 545957564
Paprika Recipe Manager: 451907567 => 451907568
Patterns:               429449078 => 429449079
Numbers:                409203824 => 409203825
Xcode:                  497799834 => 497799835
```

And these stayed the same:

```
Battery Time Remaining 2: 665678267
Soulver:                  413965349
unDock:                   402359583
```

**Comment by beejhuff** [comment]
I'm showing the same thing for Numbers:

```Bryan-BJ-Hoffpauirs-MacBook-Pro:~ hoffpauirb$ mas list
409203825 Numbers (4.0.5)
408981434 iMovie (10.1.4)
409183694 Keynote (7.0.5)
682658836 GarageBand (10.1.4)
409201541 Pages (6.0.5)
441258766 Magnet (1.10.2)
```

Note this is on my work machine which I picked up after being freshly set up by IT last week of December.  I don't recall updating anything myself so I'm guessing whatever IT did to install the base Mac Office apps is what I'm showing.  

Although that limits my ability to verify if my ID's changed it might suggest the change (for at least some accounts) occurred earlier than originally reported here.

**Comment by reitermarkus** [comment]
These are from my dotfiles, they haven't changed in over a year, so I think this is/was a bug.

```
409203825 Numbers
497799835 Xcode
```
