### ISSUE TITLE
`signin` only works on Sierra if using dialog

### ISSUE THREAD

**Issue by jd20** [mas-cli/mas#78]
On a fresh Sierra install (10.12.3), if I do the command line `mas signin`, I am still being prompted for my password when installing apps. (Even though `mas signin` is reporting I'm already signed in.)

If I then sign out, and run `mas signin --dialog`, I don't observe this problem (apps install just fine without any further prompts).

**Comment by tcamin** [comment]
+1 here

**Comment by phatblat** [comment]
Dup of #129. Moving conversation over there.
