### ISSUE TITLE
Non-ASCII characters search

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#79]
When I run `mas search` command with Non-ASCII keywords, it is common that no results were found. But when I search in MAS app, there are many results matching the keywords. Can you fix this?

**Comment by rodionovd** [comment]
Hello @clavichord93, thanks for reaching us out!

Unfortunately I was unable to reproduce the issue you described: I've just tried to search for "中文百科"  with both `mas` and MAS app and they both returned the same result: [中文百科 - for Wikipedia](https://itunes.apple.com/us/app/中文百科-for-wikipedia/id1206219720?l=en&mt=12)

```
$ mas search 中文百科
1206219720 中文百科 - for Wikipedia
```

--------

 I guess the point of confusion here is that `mas search` looks for *app names* only and not their descriptions/keywords:

```
$ mas search
Missing argument for the app name to search
```

If you believe that `mas` needs a full-text search support, please file a feature request in a new issue.

Thank you!
