### ISSUE TITLE
`list` segmentation fault

### ISSUE THREAD

**Issue by berstend** [mas-cli/mas#82]
Hi there,
all mas commands run fine with the exception of `mas list`, which is seg faulting.

Any way to help debugging without compiling from source? 😊 

```
❯❯❯ mas version
1.3.1

❯❯❯ mas account
-stripped-

❯❯❯ mas list
[1]    5424 segmentation fault  mas list
```

Resetting or signin/signout does not fix it.

Thanks!

**Comment by lwolfsonkin** [comment]
I'm getting the same problem. I just installed `mas` and this is what I get:

```bash
$ mas version
1.3.1
```

```bash
$ mas list
408981381 iPhoto (9.6.1)
682658836 GarageBand (10.1.2)
408981434 iMovie (10.1.2)
497799835 Xcode (7.3.1)
409201541 Pages (5.6.2)
409183694 Keynote (6.6.2)
fish: 'mas list' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by mindrunner** [comment]
I can confirm this partly. Running in my VMware VMs, 'mas list' segfaults. On physical hardware, it doesn't... Anyone already debugging this?

**Comment by edrozenberg** [comment]
Same issue here, segfaulting on a couple different machines, both on 10.12.6. Guessing some recent Sierra update has led to the problem.

**Comment by lwolfsonkin** [comment]
I'm still on El Capitán, so I don't think it's a Sierra bug necessarily.

2017-08-25 19:55 GMT-04:00 Eduard Rozenberg <notifications@github.com>:

**Comment by wesbaker** [comment]
For the folks that have this, do you have a macOS installer downloaded? I think that was my problem. When I attempted to run `mas list`, this is what I got:

```shell
$ mas list                                                                                                                                                                      (254ms)
1063661581 Renamer 5 (5.1.0)
931657367 Calcbot (1.0.6)
1081413713 GIF Brewery 3 (3.6)
880001334 Reeder (3.0.5)
451907568 Paprika Recipe Manager (2.2.0)
407963104 Pixelmator (3.7)
497799835 Xcode (9.0)
585829637 Todoist (7.0.3)
557168941 Tweetbot (2.5.3)
1263070803 Lungo (1.3.0)
924726344 Deliveries (3.0.5)
1017470484 Next Meeting (1.9.2)
889428659 xScope (4.3)
425424353 The Unarchiver (3.11.3)
1179623856 Pastebot (2.1.4)
fish: 'mas list' terminated by signal SIGSEGV (Address boundary error)
```

When I compiled from source and ran it, I got this (notice what's below Pastebot):
```shell
./build/mas list                                                                                                                                                                 (10s 79ms)
1063661581 Renamer 5 (5.1.0)
931657367 Calcbot (1.0.6)
1081413713 GIF Brewery 3 (3.6)
880001334 Reeder (3.0.5)
451907568 Paprika Recipe Manager (2.2.0)
407963104 Pixelmator (3.7)
497799835 Xcode (9.0)
585829637 Todoist (7.0.3)
557168941 Tweetbot (2.5.3)
1263070803 Lungo (1.3.0)
924726344 Deliveries (3.0.5)
1017470484 Next Meeting (1.9.2)
889428659 xScope (4.3)
425424353 The Unarchiver (3.11.3)
1179623856 Pastebot (2.1.4)
0 Install macOS High Sierra (13.0.64)
419330170 Moom (3.2.9)
420212497 Byword (2.8.1)
873245660 Spillo (2.0)
890031187 Marked 2 (2.5.10)
409201541 Pages (6.3)
413965349 Soulver (2.6.4)
803453959 Slack (2.8.1)
1055511498 Day One (2.5.1)
942305623 Thessa (1.4)
411643860 DaisyDisk (4.4)
405399194 Kindle (1.20.3)
992076693 MindNode (2.5.5)
409203825 Numbers (4.3)
443987910 1Password (6.8.2)
409183694 Keynote (7.3)
1091189122 Bear (1.3.1)
1107421413 1Blocker (1.4)
```

So my guess is that the macOS installers (or possibly other apps?) don't have a `product.itemIdentifier` and we get a segmentation fault.

**Comment by wesbaker** [comment]
Sure enough, when I delete the installer, `mas list` works like before.

**Comment by lwolfsonkin** [comment]
That's very likely it. I have been a hold out on El Capitan, and the new
macOS installer is likely there. Great catch, Wes!

בתאריך יום ג׳, 10 באוק׳ 2017 ב-11:39 מאת Wes Baker <notifications@github.com

**Comment by mraerino** [comment]
I can confirm this.
I'm on Sierra and recently downloaded the High Sierra installer.

**Comment by berstend** [comment]
Note sure if this behavior is related to the initial segfault I reported here but in my case the `mas list/outdated` commands went silent (no more segfault, but also no output).

My system is pretty outdated and I move to a more recent one soon, so I'll add the following for historical purposes only. 😄 

```
~ ❯❯❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

~ ❯❯❯ mas version
1.3.1

~ ❯❯❯ mas account
-- stripped --

~ ❯❯❯ mas search xcode
497799835 Xcode

~ ❯❯❯ mas outdated
⏎

~ ❯❯❯ mas list                                                                                                                                                       ⏎


```

I most likely had a `macOS installer` downloaded back when I reported this issue in the first place, but can't find it currently on my system.

**Comment by csi-adziahel** [comment]
Yes, that's MacOS installer makes it crash because its' ID is 0. Worked for High Sierra Beta in Sierra and Release in both Sierra and High Sierra.

**Comment by windyinsc** [comment]
Bam! I had this very same issue`Segmentation fault: 11` and after I uninstalled my macOS Sierra installer the segmentation fault error was resolved. Hat tip to @wesbaker for the easy fix. 

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036

$ mas version
1.3.1
```

**Comment by truwo** [comment]
I could use "mas list" again on High Sierra 10.13.1 after explicitely uninstalling mas via "brew uninstall mas" followed by a "brew install mas" and deleting the "Install macOS High Sierra" App from Applications. Prior to that, I also got a segmentation violation. 
I hope that this can help you as well bridging the gap until someone takes care of an update of this (beloved and still very useful) project...

**Comment by exalted** [comment]
Moving “Install macOS High Sierra” to anywhere else will do it just fine. 🤷‍♂️ 

Nasty stuff… I am glad there‘s a workaround after all, however. 🙇

**Comment by paulp** [comment]
`brew install --HEAD mas` is at present sufficient to avoid the seg fault without moving the installer out of the way, so presumably this has been fixed and only awaits a release.

**Comment by thoke** [comment]
@paulp, what version of the installer is present such that it's working?

My installer had been removed, so I downloaded again and `mas list` is working just fine:

```
$ mas version
1.3.1

$ mas list
-->8 snip 8<--
0 Install macOS High Sierra (13.3.02)
409203825 Numbers (4.3.1)
-->8 snip 8<--
```
At some point before, I too was having the seg fault.

**Comment by paulp** [comment]
@thoke 
Current release:

```
% brew install mas
==> Downloading https://homebrew.bintray.com/bottles/mas-1.3.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mas-1.3.1.sierra.bottle.tar.gz
...
% mas list
...
407963104 Pixelmator (3.7)
Segmentation fault: 11
```

HEAD:
```
% brew install --HEAD mas
...
% mas list
...
407963104 Pixelmator (3.7)
 Install macOS High Sierra (13105)
...
```

No dots in my installer version. Maybe it's something silly like it running off the end of the buffer looking for a dot.

**Comment by paulp** [comment]
@thoke Oh, I just noticed it's also in the list with dots.
```
407963104 Pixelmator (3.7)
 Install macOS High Sierra (13105)
...
0 Install macOS High Sierra (13.1.05)
...
```

**Comment by paulp** [comment]
The relevant code (as mentioned in an earlier comment) is 
```
for product in products {
  print("\(product.itemIdentifier) \(product.appName) (\(product.bundleVersion))")
}
```
So more than likely the absent `itemIdentifier` is indeed the cause.

It's possible this has been fixed not by a change in this project, but by a change in the swift compiler. I don't know swift at all, but one can imagine both interpolation behaviors existing in different compiler versions.

**Comment by paulp** [comment]
Aha.
```
% brew install --build-from-source mas
% mas version
1.3.1
% mas list
...
407963104 Pixelmator (3.7)
 Install macOS High Sierra (13105)
...
```

**Comment by phatblat** [comment]
Is anyone still having this issue with mas 1.4.1? I'm unable to reproduce it.

```
$ mas version
1.4.1
$ mas list
...
1246284741 Install macOS High Sierra (13.4.08)
```
