### ISSUE TITLE
`signin` 2FA error

### ISSUE THREAD

**Issue by huabin** [mas-cli/mas#83]
reproduce:

1. open TWO-FACTOR AUTHENTICATION in appleid.apple.com

2. run `mas siginin appleid`

3. get the error info like title.

solve it:

close TWO-FACTOR AUTHENTICATION in appleid.apple.com

**Comment by egeesin** [comment]
I tried to login with a new app-specific password but no chance.

**Comment by veryaustin** [comment]
I have 2FA setup on my iCloud account and would love to have MAS 2FA compatibility so I can script the signin and installation of apps in the App Store

**Comment by colinbm** [comment]
Not a solution, but my workaround is to pause while manually signing in...

    brew install mas;
    open "/Applications/App Store.app";
    read -p "Ensure you are signed in to the App Store, then hit enter. ";
    mas install ...

**Comment by phatblat** [comment]
Closing in favor of #163
