### ISSUE TITLE
macOS Sierra 10.12.4 insists 'Redownload Unavailable with this Apple ID'

### ISSUE THREAD

**Issue by ghost** [mas-cli/mas#85]
mas 1.3.1 pops a graphical dialog 'This redownload is not available for this Apple ID either because it was bought bt a different user or the item was redfunded or cancelled." I had not previously downloaded this app.

I reset mas and signed in again with the gui dialog. Same result.

Choosing the app from the regulas app store and downloading it worked fine.

Angus

**Comment by phantomwhale** [comment]
Hit this issue also - as per https://github.com/mas-cli/mas#usage my issue was:

> Please note that this command will not allow you to install (or even purchase) an app for the first time: it must already be in the Purchased tab of the App Store.

So after a manual install, this now works for future installations against my Apple ID

**Comment by Willian-Zhang** [comment]
I use multiple AppleIDs of different region,  same issue with apps purchased from current inactive AppleIDs

**Comment by cbrunnkvist** [comment]
It still does not work (macOS Big Sur). This _despite_ being logged in and able to download apps using _App Store.app_, and `mas account` picking up the correct primary account. 

I can again **confirm** that it is pristine app downloads that fail with this (erroneous) message - already "purchased" apps download perfectly fine! 😵

<img width="466" alt="Screen Shot 2021-08-25 at 17 36 07" src="https://user-images.githubusercontent.com/34006/130777526-a603f191-6cf9-4168-8555-9584ed8ebf18.png">

**Comment by cbrunnkvist** [comment]
Is this bug somehow related to `trackViewUrl`, which always seem to contain an `/en/` component e.g. 
```
$ mas info 1456732565
Zerion: Crypto DeFi Wallet 1.29 [0.0]
By: Zerion LLC
Released: 2021-08-16
Minimum OS: 13.0
Size: 71.6 MB
From: https://apps.apple.com/us/app/zerion-crypto-defi-wallet/id1456732565?uo=4
```

BUT
when I select _Share -> Copy link_ in App Store app, the link produced contains the country code of my current account
```
https://apps.apple.com/th/app/zerion-crypto-defi-wallet/id1456732565
```

(Just a theory, but: do we need to class-dump again and figure out a way install from the correct market / market-specific accountDSID or something?)
