### ISSUE TITLE
`search` fails to find Things 3

### ISSUE THREAD

**Issue by phatblat** [mas-cli/mas#90]
I tried to install Things 3 using mas, but was unable to find it using the `search` command.

```zsh
% mas version
1.3.1

% mas search Things
892274130 All Things Money Lite
1107759193 Doo - Get Things Done
534503545 Little Things® Forever
406138521 Thinkin' Things 1
782925777 All Things Money
980940463 Convert Things
515203479 Cheats for words: when you Draw things with friends
1020146983 Explain 3D How things work
577932305 Todo Things
435972315 The Next Big Thing - Lite
1216895742 Things Speak
430203668 The Next Big Thing

% mas search "Things 3"
1020146983 Explain 3D How things work

% mas search Things3
No results found
Error: No results found
```

After grabbing the product identifier from the [MAS link](https://itunes.apple.com/us/app/things-3/id904280696?mt=12) I was able to install it.

```zsh
% mas search 904280696
No results found
Error: No results found

% mas install 904280696
==> Downloading Things 3
==> Installed Things 3

% mas list | grep Things
904280696 Things3 (3.0.1)
```

Things 3 was just released a couple days ago. Does the search command use a cached list of apps?

- mas 1.3.1 (via brew)
- macOS 10.12.5
- iMac 27-inch, Late 2012

**Comment by nicolinuxfr** [comment]
Same problem here. I had to use the Mac App Store…

**Comment by bensleveritt** [comment]
Whoa, so this isn't unique to me. Interesting 🤔

**Comment by Eitot** [comment]
Seems to be an external problem: https://github.com/mas-cli/mas/blob/4e71d2c9d4a10953ee453596d00ddfc67bab2efc/mas-cli/Commands/Search.swift#L46

**Comment by nebbers1111** [comment]
Digging around with the link Eitot pointed to, seems to suggest that Things 3 is not being found because it does not have a trackName, instead has a trackCensoredName which is not looked at because of `&attribute="allTrackTerm"`

**Comment by nicolinuxfr** [comment]
Same problem for ScreenFlow… 

<img width="738" alt="capture d ecran 2017-08-02 a 13 32 49" src="https://user-images.githubusercontent.com/2078386/28871933-168180f0-7787-11e7-89bd-41d260c8a2d3.png »>

Maybe it’s a catalogue issue ? The new version of this app is really recent : https://itunes.apple.com/app/screenflow-7/id1223627207?mt=12

Installation was fine then, using the id.
