### ISSUE TITLE
Can't find Things 3

### ISSUE THREAD

**Issue by driesvints** [mas-cli/mas#94]
Heya, I tried searching for Things 3 through `mas` but it can't seem to find it. Tried resetting a few times but without any luck. Any idea why it doesn't finds this particularly app?

**Comment by nicolinuxfr** [comment]
No idea, but you're not alone and it was already reported… :-) https://github.com/mas-cli/mas/issues/90

**Comment by driesvints** [comment]
So sorry for the double issue! 🤐
