### ISSUE TITLE
Homebrew previously required Xcode to install mas via a build

### ISSUE THREAD

**Issue by raisedadead** [mas-cli/mas#98]
```
$ brew install mas
Updating Homebrew...
mas: A full installation of Xcode.app 8.0 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
```

I am aware that this is unsupported, but reporting just to discuss and understand the intention.
This would be a huge disappointment because I would not need the the entire app post installing the mas-cli.

Any thoughts?

I know it would be easier to manually install all of the purchased apps on the App Store instead of doing the 4.5 GB of download and installation.

**Comment by raisedadead** [comment]
Apologies just found out that instead of a Homebrew installation I could use the binaries.
Can we then have additional instructions on copying the cli to `/usr/local/bin`?

That should help!?

**Comment by vinkla** [comment]
I had the exact same issue when setting up a fresh install of macOS. Isn't it possible to install `mas` without having `Xcode.app` installed? `xcode-select --install` should be enough right?

**Comment by raisedadead** [comment]
> The command xcode-select --install should be enough right?

Unfortunately not, apple seems to have removed support for building binaries with the command line tools, and hence the requirement of the full Xcode installation which is ridiculous.

The current way seems to be developers providing built binaries of the same. 

I tried a pre-built version of the mas-cli and that seems to work.

**Comment by vinkla** [comment]
> I tried a pre-built version of the mas-cli and that seems to work.

Is it possible to install the pre-built version with Homebrew?

**Comment by Basilmir** [comment]
@raisedadead  Apple didn't "remove support for building binaries with the command line tools". They removed "Xcode command line tools" entirely. These can be intalled with a fresh install of Xcode or downloaded from the Developer Center separately.

**Comment by fernandopasik** [comment]
It's working on the final version of High Sierra. Shouldn't this issue be closed?

**Comment by raisedadead** [comment]
@Basilmir thanks, yes as I mention in the OP its a 4.5 GB of download / install and software that I would be needed to keep using mas-cli.

So, this basically would be worthless to do from a productivity point of view. Hence this issue to remove the dependency.
 
That said, I have gone back to Sierra from High Sierra, hence this is personally not an issue to me, also I am no longer using the `mas-cli` anymore owing to no response from any of the maintainers.

Since @fernandopasik mentions that this is resolved, I am closing it.

Cheers.!
